### ISSUE TITLE
gzip: stdout: No space left on device

### ISSUE THREAD

**Issue by whiteghost1** [pocopico/tinycore-redpill#1]
Hello. I am using vdmk file in Virtual box.
i run ./rploader.sh build bromolow-7.0.1-42218 and get error
[#] Creating loader image at loader.img ...
gzip: stdout: No space left on device

tc @ box: ~ $ df -h
Filesystem Size Used Avail Use% Mounted on
rootfs 894M 894M 0 100% /
How to fix?

**Comment by pocopico** [comment]
Hi, how did you end up with this ? The available space on /home/tc is usually 1.8G 

Do an ./rploader.sh clean now and retry

**Comment by whiteghost1** [comment]
after reboot
Filesystem      Size  Used Avail Use% Mounted on
rootfs          894M   40M  855M   5% /
tmpfs           497M     0  497M   0% /dev/shm
/dev/sda3       9.7G   52M  9.6G   1% /mnt/sda3
/dev/loop0       24K   24K     0 100% /tmp/tcloop/attr
.....

sda3 i manualy resize, but it did not help 
after run 
tc@box:~$  ./rploader.sh build bromolow-7.0.1-42218
Loader source : https://github.com/jumkey/redpill-load.git Loader Branch : develop
Redpill module source : https://github.com/RedPill-TTG/redpill-lkm.git : Redpill module branch : master
......
[#] Dumping ds3615xs_42218 platform extensions to /home/tc/redpill-load/build/1641841436/custom-initrd/exts... [OK]
[#] Packing custom ramdisk layer to /home/tc/redpill-load/build/1641841436/custom.gz... [OK]
[#] Generating GRUB config... [OK]
[#] Creating loader image at loader.img...
gzip: stdout: No space left on device

tc@box:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs          894M  894M     0 100% /
tmpfs           497M     0  497M   0% /dev/shm
/dev/sda3       9.7G   52M  9.6G   1% /mnt/sda3

how to resize rootfs?

**Comment by pocopico** [comment]
Since you are using VMware,and rootfs is a percentage of the available memory,  I guess you could increase the ram size of the VM ?

**Comment by whiteghost1** [comment]
Yes. it worked. Thank you
