### ISSUE TITLE
Running VMDK file issue on VMware Esx server

### ISSUE THREAD

**Issue by Plarkass** [pocopico/tinycore-redpill#11]
Hello,

i cannot run TinyCore on esx server, 
I got an issue with message below

Failed - Unsupported or invalid disk type 2 for 'scsi0:0'. Ensure that the disk has been imported.

Errors
Unsupported or invalid disk type 2 for 'scsi0:0'. Ensure that the disk has been imported.
Unable to create virtual SCSI device for 'scsi0:0' (/vmfs/volumes/6157af2c-e9b2842a-d29b-10604b890a0c/TinyCoreRedPill/tinycore-redpill.v0.4.4.vmdk).
Module 'DevicePowerOn' power on failed.
Failed to start the virtual machine.

**Comment by gauchim** [comment]
You must attach vmdk as IDE0

**Comment by Plarkass** [comment]
Thanks a lot, it work and also i have to switch to bios instead of UEFI

**Comment by Plarkass** [comment]
Thanks a lot, it work and also i have to switch to bios instead of UEFI
