### ISSUE TITLE
please update the tinycore version of tinycore-redpill.v0.8.0.0.img.gz to 13.1

### ISSUE THREAD

**Issue by tocaata** [pocopico/tinycore-redpill#112]
My PC has two network card rtl8156B and intel i225-v. In the tinycore 13.1, there are kernel drivers for the two cards.
But tinycore-redpill.v0.8.0.0.img.gz lose the driver. I can not build the DSM boot img for my PC.
Thanks!

**Comment by yanshibin** [comment]
same problem
