### ISSUE TITLE
Ethernet interface no matching extension

### ISSUE THREAD

**Issue by Cryental** [pocopico/tinycore-redpill#120]
Hello.

Found Ethernet Interface : pciid 10ecd00008125 Required Extension :
No matching extension
Found Ethernet Interface : pciid 10ecd00008125 Required Extension :
No matching extension 

I'm getting this error and it should recognize this correctly to r8125. Can you please fix this error? Thank you!

**Comment by Viking8** [comment]
I've been trying to get geminilake-7.1.0-42261 (DS920+) with an rtl8125 based card to work as well, but it just won't detect it. I tried adding it, but the message I received made it sound like the driver was already there and not needed. For some reason I can't get an address from the other two built in NIC's on the mobo either. Doesn't matter if I make the boot drive with or without the rtl8125 card installed.

Mobo: EVGA Z270 FTW-K
NIC 1: intel i219 
NIC 2: Killer E2500

Everything works fine using the DS918+ setup, except I didn't have the realtek card when I set it as a DS918+, so I haven't tested that yet. Besides the rtl8125 issue, would you have any ideas as to what I could do to my redpill boot drive to get the built-in NIC's to grab an IP? doing a listmods detected them, and added an alx driver for the Killer NIC and an e1000e driver for the intel NIC. It didn't even see the rtl8125.

**Comment by Viking8** [comment]
Pocopico? Any help would be gratefully appreciated. Thx!

**Comment by pocopico** [comment]
Can you try on a platform that includes four network interfaces like 3622 ?

**Comment by Viking8** [comment]
Output from ./rploader.sh listmods broadwellnk-7.1.0-42661

![image](https://user-images.githubusercontent.com/23368970/183526103-2fa81bb4-6d0d-4e5d-9a2e-10a602af9ce9.png)

**Comment by Viking8** [comment]
Pocopico, what do should I try next?

**Comment by Viking8** [comment]
Sorry to bug you Pp, I just really want to get this up and running so I can test it as soon as possible.

**Comment by pocopico** [comment]
What if you manually add 

https://raw.githubusercontent.com/pocopico/rp-ext/master/r8125/rpext-index.json

Can you also please use a platform that natively supports more than two network interfaces ?

**Comment by Viking8** [comment]
I guess you missed the message above where I mentioned trying to manually add the driver. Unfortunately, I've tried several times without success. Also, every time I've tried, I've added the other NIC's to the user config file in the same format as the one it detects. I've made sure to use the real mac addresses as well. 

Which platform would you suggest? 

Mobo: EVGA Z270 FTW-K
NIC 1: intel i219
NIC 2: Killer E2400

PCI-e cards:
NIC3: Realtek rtl8125 2.5 Gbe - pciid: 10ecd00008125

**Comment by Cryental** [comment]
Manual load is working, just the bash script doesn't detect the correct version.
