### ISSUE TITLE
Have I discovered a bug in satamap?

### ISSUE THREAD

**Issue by SonicWim** [pocopico/tinycore-redpill#133]
When I try to upgrade from DSM 5.2 to the latest version via tinycore-redpill-uefi.v0.8.0.0 I get an error executing the satamap command when I updated everything and use script version 0.8.0.5, it looks like the array $pcis is not being correctly parsed, it seems to cut it up in multiple pieces at space characters, I've added a few DEBUG echo statements to display the $pcis and $pci variables while looping through them at line 1312 of the script and the for block afterwards.

```   
    # loop through non-SATA controllers
    echo -e "\nDEBUG: $pcis\n"
    for pci in $pcis; do
        echo -e "\nDEBUG: $pci\n"
```

```
tc@box:~$ ./rploader.sh satamap
Found SCSI HBAs, We need to install the SCSI modules
scsi-5.10.3-tinycore64 is already installed!
Succesfully installed SCSI modules

Found "00:1f.2 Intel Corporation 7 Series/C210 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)"
Detected 6 ports/5 drives. Bad ports: 6. Override # of ports or ENTER to accept <6>


DEBUG: 01:01.0 RAID bus controller: Silicon Image, Inc. SiI 3114 [SATALink/SATARaid] Serial ATA Controller (rev 02)


DEBUG: 01:01.0

Found SCSI/HBA "01:01.0 Silicon Image, Inc. SiI 3114 [SATALink/SATARaid] Serial ATA Controller (rev 02)" (4 drives)

DEBUG: RAID

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: bus

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: controller:

lspci: -s: Invalid bus number
Found SCSI/HBA "" (0 drives)

DEBUG: Silicon

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: Image,

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: Inc.

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: SiI

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: 3114

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: [SATALink/SATARaid]

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: Serial

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: ATA

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: Controller

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: (rev

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

DEBUG: 02)

lspci: -s: Invalid slot number
Found SCSI/HBA "" (0 drives)

Computed settings:
SataPortMap=6
DiskIdxMap=00

WARNING: Bad ports are mapped. The DSM installation will fail!

Should i update the user_config.json with these values ? [Yy/Nn] y
Done.
```

In the shell the HBA disks get properly mapped, I have 9 + 1 (the USB stick) of them when I execute ```ls -la /sys/block | grep "sd"```

Besides that everything works but when DSM is installed it only sees the 5 disks connected to the internal controller and not the 4 extra disks connected to the HBA.

Or am I doing something wrong?

**Comment by pocopico** [comment]
You need sata_sil and libata modules. There is no extension for that.

**Comment by SonicWim** [comment]
I see, but it confuses me a bit...
I've been following [this](https://xpenology.com/forum/topic/62221-tutorial-installmigrate-to-dsm-7x-with-tinycore-redpill-tcrp-loader/) tutorial and there they speak about driver extensions AKA modules to add that are listed on [this](https://github.com/pocopico/rp-ext) page but I can't find the 2 you mentioned, sata_sil and libatat. Or are those kernel modules?

Is there a place where I can find more info about this because I searched for quite a while but haven't found anything useful yet.
