### ISSUE TITLE
When to support the latest 7.1.1 system

### ISSUE THREAD

**Issue by PWMFI** [pocopico/tinycore-redpill#146]

**Comment by pocopico** [comment]
What do u mean ? 7.1.1 is already supported

**Comment by PWMFI** [comment]
> 

Cannot support the latest version: 7.1.1-42962

**Comment by PWMFI** [comment]
> 你是什么意思？已支持 7.1.1

The ds3617xs needs to upgrade to 7.1.1. After installation, you will be prompted that restore cannot enter the system. How to compile the latest boot? Is there a new tool available

**Comment by PWMFI** [comment]
> 你是什么意思？已支持 7.1.1

![微信图片_20220922084513](https://user-images.githubusercontent.com/63692121/191634360-479d9001-2cac-49f1-9a96-8d6acfd7cf91.jpg)

**Comment by PWMFI** [comment]
![4614724aad8f46e2d126e834a078acf](https://user-images.githubusercontent.com/63692121/191637634-148c310e-c322-4f77-80c0-41a3f67226f0.jpg)

**Comment by PWMFI** [comment]
Is there a solution

**Comment by dlutwang** [comment]
> Is there a solution

plz use develop tree, not the master tree

**Comment by PWMFI** [comment]
> > Is there a solution
> 
> plz use develop tree, not the master tree

Where? Is there a link

**Comment by keniji** [comment]
> > > Is there a solution
> > 
> > 
> > plz use develop tree, not the master tree
> 
> Where? Is there a link

Try this:
[https://github.com/pocopico/tinycore-redpill/tree/develop]()
