### ISSUE TITLE
/home/tc/redpill-load/config/_common/v7.7.1/ramdisk-003-post-init-script-noatime.patch - failed to apply

### ISSUE THREAD

**Issue by rockvegas007** [pocopico/tinycore-redpill#152]
While running he command bellow for DS3617xs :

sudo. /rploader.sh build broadwell-7.1.1-42962

Error: 

[#] Apply patches to /home/tc/redpill-load/build/1664341272/rd-ds3617xs_42962-unpacked... include/patch.sh: line 52: /home/tc/redpill-load/config/_common/v7.7.1/ramdisk-003-post-init-script-noatime.patch: No such file or directory

[!] One of the patches - /home/tc/redpill-load/config/_common/v7.7.1/ramdisk-003-post-init-script-noatime.patch - failed to apply

*** Process will exit ***

**Comment by pablotoribio-beta** [comment]
I have the same problem

**Comment by pocopico** [comment]
Fixed the typo
