### ISSUE TITLE
No network after build and reboot on DS3622xs+

### ISSUE THREAD

**Issue by DidaJI** [pocopico/tinycore-redpill#154]
I have a problem with "RedPill DS3622xs+ v7.1.1-42962 Beta (USB, Verbose)" booting properly. 

Here is a listing of where it stops from the serial console:
3.057422] Trying to unpack rootfs image as initramfs...
[    3.076107] Freeing initrd memory: 25912K
[    3.081179] redpill: loading out-of-tree module taints kernel.
[    3.087073] redpill: module verification failed: signature and/or required key missing - tainting kernel
[    3.097874] Kernel panic - not syncing: Fatal exception
[    3.103114] CPU: 5 PID: 769 Comm: insmod Tainted: G           OE   4.4.180+ #42962
[    3.110714] Hardware name: Gigabyte Technology Co., Ltd. B560M DS3H V2/B560M DS3H V2, BIOS F7 03/25/2022
[    3.120171]  0000000000000000 ffff880893207c60 ffffffff812dce6b ffffffffa000c0a2
[    3.127810]  ffff8808958290c0 ffff880893207cd8 ffffffff811217f7 0000000000000008
[    3.135437]  ffff880893207ce8 ffff880893207c88 ffff880893207ce8 ffffffffa000c3a0
[    3.143111] Call Trace:
[    3.145611]  [<ffffffff812dce6b>] dump_stack+0x4d/0x72
[    3.150744]  [<ffffffff811217f7>] panic+0xc6/0x21e
[    3.155544]  [<ffffffffa0013000>] ? 0xffffffffa0013000
[    3.160688]  [<ffffffffa0013019>] ? init_+0x19/0xde [redpill]
[    3.166441]  [<ffffffff81000340>] ? do_one_initcall+0x80/0x130
[    3.172321]  [<ffffffff810bf26b>] ? do_init_module+0x5b/0x1d0
[    3.178116]  [<ffffffff810c1044>] ? load_module+0x1be4/0x2080
[    3.183896]  [<ffffffff810bdef0>] ? __symbol_put+0x40/0x40
[    3.189382]  [<ffffffff8118a4ac>] ? kernel_read+0x3c/0x50
[    3.194817]  [<ffffffff810c169d>] ? SYSC_finit_module+0x7d/0xa0
[    3.200720]  [<ffffffff810c16d9>] ? SyS_finit_module+0x9/0x10
[    3.206470]  [<ffffffff81566d8a>] ? entry_SYSCALL_64_fastpath+0x1e/0x8e
[    3.213294] ---[ end Kernel panic - not syncing: Fatal exception

Do you know what it could be?
HW:
MB: Gigabyte B560M DS3H V2
CPU: Intel i5 10400
RAM: 32GB

Thanks for the reply, Zdenek.

**Comment by pocopico** [comment]
There was an issue with the config files for DS3622xs+ and it has beem fixed. Please retry
