### ISSUE TITLE
V0.9.2.5 After compilation, the (loader. img) file cannot be exported as before. I need to export this file separately. How do I generate this file? Thank you

### ISSUE THREAD

**Issue by PWMFI** [pocopico/tinycore-redpill#155]
![微信图片_20220929183428](https://user-images.githubusercontent.com/63692121/193009429-9423d698-40ae-4890-bb6e-cc40c99fe914.jpg)

**Comment by pocopico** [comment]
Please comment or remove line 2723 and you'll be fine.
