### ISSUE TITLE
Need to Change URLs in Scripts. "master" is being phased out or already deprecated.

### ISSUE THREAD

**Issue by tlsnine** [pocopico/tinycore-redpill#16]
Github has discontinued the use of "master/slave" so the URLs need to be updated to "main" instead.

IE: The json file `https://github.com/pocopico/rp-ext/blob/**main**/ixgbe/rpext-index.json` has references to `https://raw.githubusercontent.com/pocopico/rp-ext/**master**/ixgbe/rpext-index.json` which while working as of this post is likely to become a victim of 404.

Some scripts are already failing because of this. Sorry, I can't remember which ones offhand.

Please update your scripts and json files to reflect the new naming conventions.

Thanks!!

**Comment by pocopico** [comment]
Ok, I will check. Thanks
