### ISSUE TITLE
Where is the loader.img?

### ISSUE THREAD

**Issue by Educateur13** [pocopico/tinycore-redpill#163]
Did you remove the ability to recover the image?
With the other versions, I would recover the image in redpill-load/loader.img, It is no longer there?
Can you tell me where the loader.img is?
Thanks

**Comment by srctar** [comment]
> Did you remove the ability to recover the image? With the other versions, I would recover the image in redpill-load/loader.img, It is no longer there? Can you tell me where the loader.img is? Thanks

it wa removed at `rploader.sh`: `echo -n "Removing loader.img -> "`,  remove it, you may find loader.img

**Comment by Educateur13** [comment]
> > Did you remove the ability to recover the image? With the other versions, I would recover the image in redpill-load/loader.img, It is no longer there? Can you tell me where the loader.img is? Thanks
> 
> it wa removed at `rploader.sh`: `echo -n "Removing loader.img -> "`, remove it, you may find loader.img

Thanks, 

` if [ -f /home/tc/redpill-load/loader.img ]; then
        echo -n "Removing loader.img -> "
        sudo rm -rf /home/tc/redpill-load/loader.img
        [ ! -f /home/tc/redpill-load/loader.img ] && echo "OK !!!"
    fi
`

` if [ -f /home/tc/redpill-load/loader.img ]; then
        
         sudo rm -rf /home/tc/redpill-load/loader.img
        [ ! -f /home/tc/redpill-load/loader.img ] && echo "OK !!!"
    fi
`

even modifying, the loader.img file is not present.
