### ISSUE TITLE
Error : Platform not found

### ISSUE THREAD

**Issue by chdeast** [pocopico/tinycore-redpill#177]
tc@box:~$ sudo ./rploader.sh build apollolake-7.1.1-42962
bspatch does not exist, bringing over from repo
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 10232 100 10232 0 0 11073 0 --:--:-- --:--:-- --:--:-- 11061
Error : Platform not found
rploader.sh

Version : 0.9.2.9
----------------------------------------------------------------------------------------
Usage: ./rploader.sh <action> <platform version> <static or compile module> [extension manager arguments]

**Comment by pocopico** [comment]
You now have to use the model number e.g

./reloaded.sh ds918p-7.1.1-42962

**Comment by chdeast** [comment]
> 

Thank you very much。

**Comment by WizardBrew** [comment]
./reloaded.sh build ds918p-7.1.1-42962 This is not working. 

![image](https://user-images.githubusercontent.com/91134716/236192134-74ab5ca0-f885-42c3-908c-a4f0b9014d9c.png)

**Comment by WizardBrew** [comment]
I have tried rploader still doesn't work can you plz check i have posted
image as well.
Plz need help.
