### ISSUE TITLE
Platform not found for broadwellnk-7.0.1-42218

### ISSUE THREAD

**Issue by neildeadman** [pocopico/tinycore-redpill#179]
I am fairly new to building Xpenology, and had been using v0.9.2.7 of Redpill with `./rploader.sh build broadwellnk-7.0.1-42218` successfully. This was using a test system just to learn the basics.

Today I am starting to build out a real system to use, but when I use v0.9.2.9 it now gives me `Platform not found`

I am building a DS3622xs+ system.

These are the commands I am running:

```
./rploader.sh update now
./rploader.sh fullupgrade now
./rploader.sh serialgen DS3622xs+
./rploader.sh identifyusb now
./rploader.sh satamap now
./rploader.sh build broadwellnk-7.0.1-42218
```

**Comment by safadi63** [comment]
The platform name is now changed
Please check by using:
./rploader.sh
![sc1](https://user-images.githubusercontent.com/34957405/197768158-418c032e-33b1-452a-b177-585310ca90ec.png)

**Comment by neildeadman** [comment]
Now I feel stupid.... I'm just following guides online and sticking to what I had working before! Thanks for that, and sorry for wasting anyones time :(

**Comment by Meissersam** [comment]
> 

I had the same problem. The guide says "architecture". I also tried DS3622xs by mistake, the correct one was DS3622xsp so I lost 15 min reading the terminal to see what happened. It is so. cheer up.
