### ISSUE TITLE
When installing DSM, it prompts: DSM cannot be installed. This file cannot be installed. The file may be damaged.

### ISSUE THREAD

**Issue by itv3** [pocopico/tinycore-redpill#189]
I am using ProxmoxVE 7.21, download the latest tinycore-redpill.v0.9.2.9.img, if the img file is virtualized into usb mode to boot, the compilation will be completed, but when uploading the installation package, it always prompts: DSM cannot be installed. Install this file, the file may have been corrupted, and it got stuck here after several tries. Tried other models with the same problem.
    If you import tinycore-redpill.v0.9.2.9.img into a sata hard disk file with qm importdisk to start the boot, there will be no problem with the installation after compilation.
Compile method:
a. Update the TCRP script
./rploader.sh update
b. Update TCRP support files
./rploader.sh fullupgrade
c. Modify the configuration file user_config.json
d. Add v9fs driver
./rploader.sh ext dva3221-7.1.1-42962 add https://raw.githubusercontent.com/pocopico/rp-ext/master/v9fs/rpext-index.json
f. Compile
./rploader.sh build dva3221-7.1.1-42962

usb boot method:
(regardless of using:
args: -device 'qemu-xhci,addr=0x18' -drive 'id=synoboot,file=/var/lib/vz/images/tinycore-redpill.v0.9.2.9.img,if=none,format=raw ' -device 'usb-storage,id=synoboot,drive=synoboot,bootindex=5'

or:

args: -device 'nec-usb-xhci,id=usb-bus0,multifunction=on' -drive 'file=/var/lib/vz/images/tinycore-redpill.v0.9.2.9.img,media=disk ,format=raw,if=none,id=drive-disk-bootloader' -device 'usb-storage,bus=usb-bus0.0,port=1,drive=drive-disk-bootloader,id=usb-disk- bootloader,bootindex=999,removable=on'
it's the same)

Compile, but after uploading the installation package, it always prompts during installation: Cannot install DSM This file cannot be installed, the file may have been damaged, and it is stuck here after several attempts
![1](https://user-images.githubusercontent.com/102932260/200517727-4041d3a1-c73d-47c3-b544-b50df64d20fe.jpg)

**Comment by shiyeah** [comment]
usb need vid and pid. sata doesn't

**Comment by itv3** [comment]
> usb need vid and pid. sata doesn't

I set the pid to 0x0001 and the vid to 0x46F4, and the installation was successful after recompiling
