### ISSUE TITLE
issue booting after writing .img file to usb

### ISSUE THREAD

**Issue by chickey** [pocopico/tinycore-redpill#2]
I've tried writing the .img file on both linux and windows, using popsicle/win32disk imager and balena etcher but every time it writes successfully but it's not bootable.  Am i being stupid and missing something obvious?

I've looked at the drives after writing and can see the 3 partitions created.

Great project btw and thankyou.

**Comment by pocopico** [comment]
Hi, sorry not very clear, are you using latest image ? If not download and burn again. Also are you using legacy or EFI boot ?

**Comment by chickey** [comment]
I was using EFI boot on two test machines.  I tested the same USB key i had created this morning on legacy boot and it booted fine.  I notice you've updated the boot flags, i had tried that on one partition in gparted also but will test the drive on a fresh usb stick with the EFI machine if it should work on it.

btw i was using the current img file from this repo 

tinycore-redpill.v0.4.4.img.gz

Thanks
Colin

**Comment by recoco** [comment]
same problem for me. please help.

**Comment by tlsnine** [comment]
I had a similar issue on a Denverton-based supermicro server. 
I updated the bios, set to default, enabled CSM Support, then I was able to boot the loader OS successfully. Hope this works for you.

**Comment by wreid23** [comment]
Hi may I ask for the tinycore-redpill.v0.4.4.img.gz file to be reuploaded as well as the VMDK they seem to be corrupted.
