### ISSUE TITLE
About SSD......

### ISSUE THREAD

**Issue by maomaoaigou** [pocopico/tinycore-redpill#207]
Hello, I use a SATA SSD, can it be installed? I'm failing at the installation stage.

**Comment by user239393** [comment]
Yes

**Comment by maomaoaigou** [comment]
> 是的

Did you install it successfully?

**Comment by user239393** [comment]
Yes on an old laptop with SATA SSD.

[DS3622xs+]
./rploader.sh update now
./rploader.sh fullupgrade now
./rploader.sh serialgen DS3622xs+
./rploader.sh identifyusb now
./rploader.sh satamap now
./rploader.sh build ds3622xsp-7.1.1-42962
./rploader.sh clean now

**Comment by maomaoaigou** [comment]
> 是的，在带有 SATA SSD 的旧笔记本电脑上。
> 
> [DS3622xs+] ./rploader.sh 立即更新 ./rploader.sh 立即 全面升级 ./rploader.sh serialgen DS3622xs+ ./rploader.sh 立即识别 ./rploader.sh 立即 satamap ./rploader.sh build ds3622xsp-7.1.1- 42962 ./rploader.sh 现在干净

Thanks! I just successfully installed it.
