### ISSUE TITLE
gzip: stdout: No space left on device

### ISSUE THREAD

**Issue by kenand1970** [pocopico/tinycore-redpill#225]
I receiving this error:
Creating unecrypted pat file dva1622_42962.pat to /home/tc/redpill-load/cache folder
gzip: stdout: No space left on device
tar: /home/tc/redpill-load/cache/dva1622_42962.pat: Wrote only 4096 of 10240 bytes
tar: Child returned status 1
tar: Error is not recoverable: exiting now

My I expand partition size of 3. partition of USB drive?

**Comment by kenand1970** [comment]
I checked again. I havve trouble with 1.3GB rootfs. It's full up.

**Comment by pocopico** [comment]
You need minimum 2GB of memory

**Comment by kenand1970** [comment]
Thanks I put 4GB RAM to Hp t610 and works
