### ISSUE TITLE
AHCI MODE

### ISSUE THREAD

**Issue by xdxxp6qp** [pocopico/tinycore-redpill#227]
to use rptc, is AHCI mode required on the motherboard?  Or is it possible without it?

**Comment by pocopico** [comment]
Depends. IDE is out of the question for 7.x. SAS is possible for non device tree models. Not possible for others.

**Comment by xdxxp6qp** [comment]
is it possible to install dsm 6.2.4?  I saw in the script for 3615, but I could not enter a command for it.  don't tell me how.

**Comment by xdxxp6qp** [comment]
I understand correctly that the rptc bootloader only works with AHCI?  Or is it bypassed only for dsm 7?  and the bootloader has the ability to install dsm 6.2.4 with the IDE?

**Comment by pocopico** [comment]
Probably possible with the old JUN 1.03b loader

**Comment by xdxxp6qp** [comment]
May I know which team?
