### ISSUE TITLE
I am confirming that file tinycore-redpill-uefi.v0.9.4.3.img.gz contains Trojan / Virus 

### ISSUE THREAD

**Issue by Andreikinas** [pocopico/tinycore-redpill#248]
Hello, I am confirming that file tinycore-redpill-uefi.v0.9.4.3.img.gz contains Trojan / Virus. Please be aware from it.

**Comment by SkyeLim** [comment]
Same here. Please be aware, My windows defender deleted it immediately.

**Comment by WarlockCyberTutorials** [comment]
Analysis of virustotal.com, here's all ok
![image](https://user-images.githubusercontent.com/49326569/225634749-4ca8e226-d824-4288-8fb1-157afedbd865.png)

**Comment by WarlockCyberTutorials** [comment]
I'll create a vm here and analyze and post the result, if present the same problem needs to be checked

**Comment by Andreikinas** [comment]
I have downloaded it in Windows 10, and Windows security immediately found Trojan/ virus. I am not first which mentioned it. Please see attached. 
![image](https://user-images.githubusercontent.com/127836866/225696162-30f4ae24-4f57-4a8a-9f5a-8eba99a55a4c.png)

**Comment by pocopico** [comment]
There seem to be a lot of fake positive on this. I have not any intention to convince you, there are a lot of propos using that alrea

**Comment by Andreikinas** [comment]
it's not fake, I am real person, and I have attached screenshot from my pc

**Comment by SkyeLim** [comment]
Look I have just captured my screenshot. your latest UEFI version has one, Windows 11 detected


<img width="411" alt="image" src="https://user-images.githubusercontent.com/128048468/225906058-348a2687-8b68-411a-88c4-82484a182e73.png">

**Comment by pocopico** [comment]
![image](https://user-images.githubusercontent.com/67732101/226100731-bebfa507-c57f-4def-8965-e56f975a18fd.png)
