### ISSUE TITLE
RAID Card support (chip ASM1064)

### ISSUE THREAD

**Issue by 0uro** [pocopico/tinycore-redpill#25]
Hello,

Great work ! very elegant and nicely done

I'm using an ASM1064-chip sata RAID pciE card, but none of the connected disks are detected. Is that related to the card ?
Should I try to fiddle with SATA addresses ?

**Comment by Isaiah333** [comment]
@0uro Are the desk not being detected in tinycore or dsm?

**Comment by 0uro** [comment]
I'm closing that issue, it has nothing to due with kernel support
