### ISSUE TITLE
Where can i find the archived version

### ISSUE THREAD

**Issue by cospotato** [pocopico/tinycore-redpill#251]
My Gen8 was using rploader 0.5.x and `bromolow-7.0.1-42218` before. I am trying to upgrade the rploader to the latest.

Then I do `./rploader.sh build `

But I do `rploader.sh backup` before I boot xpenology successfully which make me lost the old version of rploader :(

Then I tried to use `DS3615xs-7.0.1-42218` and `DS3615xs-7.0.1-42218-JUN` build. Cannot boot either.

**Comment by nemesis122** [comment]
do you need this ?
https://github.com/pocopico/tinycore-redpill/releases

https://github.com/pocopico/tinycore-redpill/releases/download/v0.9.2.6/tinycore-redpill.v0.9.2.6.img.gz
