### ISSUE TITLE
ds3622xsp-7.2.0-64551 assemble error

### ISSUE THREAD

**Issue by muzdai** [pocopico/tinycore-redpill#267]
Adding extension "https://github.com/pocopico/tcrp-addons/raw/main/all-modules/rpext-index.json",
[#] Checking runtime for required tools... [OK]
[#] Adding new extension from https://github.com/pocopico/tcrp-addons/raw/main/all-modules/rpext-index.json...
[#] Downloading remote file https://github.com/pocopico/tcrp-addons/raw/main/all-modules/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%
[OK]
[#] ========================================== all-modules ==========================================
[#] Extension name: all-modules
[#] Description: Adds All modules Support
[#] To get help visit: <todo>
[#] Extension preparer/packer: https://github.com/pocopico/tcrp-addons/tree/main/all-modules
[#] Software author: https://github.com/pocopico
[#] Update URL: https://raw.githubusercontent.com/pocopico/tcrp-addons/main/all-modules/rpext-index.json
[#] Platforms supported: dva1622_64551 rs3618xs_64551 rs3413xsp_64551 rs3621xsp_64551 ds720p_64551 ds1019p_64551 dva3221_42962 ds1019p_42218 ds3622xsp_42962 rs3618xs_42962 ds920p_42962 rs1619xsp_64551 dva3219_64551 ds923p_42962 fs2500_64551 ds1621p_64551 rs1619xsp_42962 sa6400_64551 ds723p_42962 ds2422p_42962 dva1622_42962 ds923p_64551 ds723p_64551 ds3617xs_64551 sa6400_42962 rs4021xsp_64551 fs2500_42962 rs4021xsp_42962 zendofmodel ds3615xs_42962 ds2422p_64551 sa3600_42962 ds3617xs_42962 ds1520p_42218 rs1221p_64551 ds3622xsp_64551 dva3219_42962 ds1520p_64551 ds1621xsp_42962 ds918p_64551 ds920p_42218 sa3400_42962 ds918p_42962 ds1621xsp_64551 rs1221p_42962 ds920p_64551 ds1520p_42962 sa3600_64551 ds918p_42218 rs3621xsp_42962 ds720p_42962 ds1019p_42962 ds3615xs_64551 sa3400_64551 rs3413xsp_42962 ds1621p_42962 dva3221_64551
[#] =======================================================================================

Adding extension "https://github.com/pocopico/tcrp-addons/raw/main/eudev/rpext-index.json",
[#] Checking runtime for required tools... [OK]
[#] Adding new extension from https://github.com/pocopico/tcrp-addons/raw/main/eudev/rpext-index.json...
[#] Downloading remote file https://github.com/pocopico/tcrp-addons/raw/main/eudev/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%
[OK]
[#] ========================================== eudev ==========================================
[#] Extension name: Eudev binaries
[#] Description: Eudev binaries will assist with auto module loading
[#] To get help visit: https://github.com/pocopico/tcrp-addons/main/eudev/
[#] Extension preparer/packer: https://github.com/pocopico/tcrp-addons/main/eudev/
[#] Software author: https://github.com/pocopico/tcrp-addons/main/eudev/
[#] Update URL: https://raw.githubusercontent.com/pocopico/tcrp-addons/main/eudev/rpext-index.json
[#] Platforms supported: dva1622_64551 ds1621p_42218 rs3618xs_64551 rs3413xsp_64551 rs3621xsp_64551 ds720p_64551 ds1019p_64551 ds3617xs_42218 dva3221_42962 ds1019p_42218 ds3622xsp_42962 rs3618xs_42962 ds920p_42962 rs1619xsp_64551 dva3219_64551 ds923p_42962 fs2500_64551 dva3221_42218 ds1621p_64551 rs1619xsp_42962 sa6400_64551 ds3622xsp_42218 ds723p_42962 ds2422p_42962 dva1622_42962 ds923p_64551 ds723p_64551 ds3617xs_64551 sa6400_42962 ds2422p_42218 rs4021xsp_64551 fs2500_42962 rs4021xsp_42962 zendofmodel ds3615xs_42962 ds2422p_64551 sa3600_42962 ds3617xs_42962 ds1520p_42218 rs4021xsp_42218 rs1221p_64551 ds3622xsp_64551 dva3219_42962 dva3219_42218 ds1520p_64551 ds1621xsp_42962 ds918p_64551 ds920p_42218 sa3400_42962 ds918p_42962 ds1621xsp_64551 rs1221p_42962 ds920p_64551 ds1520p_42962 sa3600_64551 ds918p_42218 rs3621xsp_42962 ds720p_42962 ds1019p_42962 ds1621xsp_42218 ds3615xs_64551 sa3400_64551 rs3413xsp_42962 ds3615xs_42218 ds1621p_42962 dva3221_64551 fs2500_42218
[#] =======================================================================================

Adding extension "https://github.com/pocopico/tcrp-addons/raw/main/disks/rpext-index.json",
[#] Checking runtime for required tools... [OK]
[#] Adding new extension from https://github.com/pocopico/tcrp-addons/raw/main/disks/rpext-index.json...
[#] Downloading remote file https://github.com/pocopico/tcrp-addons/raw/main/disks/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%
[OK]
[#] ========================================== disks ==========================================
[#] Extension name: Eudev binaries
[#] Description: Eudev binaries will assist with auto module loading
[#] To get help visit: https://github.com/pocopico/tcrp-addons/main/disks/
[#] Extension preparer/packer: https://github.com/pocopico/tcrp-addons/main/disks/
[#] Software author: https://github.com/pocopico/tcrp-addons/main/disks/
[#] Update URL: https://raw.githubusercontent.com/pocopico/tcrp-addons/main/disks/rpext-index.json
[#] Platforms supported: dva1622_64551 ds1621p_42218 rs3618xs_64551 rs3413xsp_64551 rs3621xsp_64551 ds720p_64551 ds1019p_64551 ds3617xs_42218 dva3221_42962 ds1019p_42218 ds3622xsp_42962 rs3618xs_42962 ds920p_42962 rs1619xsp_64551 dva3219_64551 ds923p_42962 fs2500_64551 dva3221_42218 ds1621p_64551 rs1619xsp_42962 sa6400_64551 ds3622xsp_42218 ds723p_42962 ds2422p_42962 dva1622_42962 ds923p_64551 ds723p_64551 ds3617xs_64551 sa6400_42962 ds2422p_42218 rs4021xsp_64551 fs2500_42962 rs4021xsp_42962 zendofmodel ds3615xs_42962 ds2422p_64551 sa3600_42962 ds3617xs_42962 ds1520p_42218 rs4021xsp_42218 rs1221p_64551 ds3622xsp_64551 dva3219_42962 dva3219_42218 ds1520p_64551 ds1621xsp_42962 ds918p_64551 ds920p_42218 sa3400_42962 ds918p_42962 ds1621xsp_64551 rs1221p_42962 ds920p_64551 ds1520p_42962 sa3600_64551 ds918p_42218 rs3621xsp_42962 ds720p_42962 ds1019p_42962 ds1621xsp_42218 ds3615xs_64551 sa3400_64551 rs3413xsp_42962 ds3615xs_42218 ds1621p_42962 dva3221_64551 fs2500_42218
[#] =======================================================================================

Adding extension "https://github.com/pocopico/tcrp-addons/raw/main/misc/rpext-index.json"
[#] Checking runtime for required tools... [OK]
[#] Adding new extension from https://github.com/pocopico/tcrp-addons/raw/main/misc/rpext-index.json...
[#] Downloading remote file https://github.com/pocopico/tcrp-addons/raw/main/misc/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%
[OK]
[#] ========================================== misc ==========================================
[#] Extension name: Misc shell
[#] Description: Misc shell
[#] To get help visit: https://raw.githubusercontent.com/pocopico/tcrp-addons/main/misc
[#] Extension preparer/packer: https://raw.githubusercontent.com/pocopico/tcrp-addons/main/misc
[#] Software author: https://raw.githubusercontent.com/pocopico/tcrp-addons/main/misc
[#] Update URL: https://raw.githubusercontent.com/pocopico/tcrp-addons/main/misc/rpext-index.json
[#] Platforms supported: dva1622_64551 ds1621p_42218 rs3618xs_64551 rs3413xsp_64551 rs3621xsp_64551 ds720p_64551 ds1019p_64551 ds3617xs_42218 dva3221_42962 ds1019p_42218 ds3622xsp_42962 rs3618xs_42962 ds920p_42962 rs1619xsp_64551 dva3219_64551 ds923p_42962 fs2500_64551 dva3221_42218 ds1621p_64551 rs1619xsp_42962 sa6400_64551 ds3622xsp_42218 ds723p_42962 ds2422p_42962 dva1622_42962 rs3413xsp_42218 ds923p_64551 ds723p_64551 ds3617xs_64551 sa6400_42962 ds2422p_42218 rs4021xsp_64551 fs2500_42962 rs4021xsp_42962 zendofmodel ds3615xs_42962 ds2422p_64551 sa3600_42962 ds3617xs_42962 rs3618xs_42218 ds1520p_42218 rs4021xsp_42218 rs1221p_64551 ds3622xsp_64551 dva3219_42962 dva3219_42218 ds1520p_64551 ds1621xsp_42962 ds918p_64551 ds920p_42218 sa3400_42962 ds918p_42962 ds1621xsp_64551 rs1221p_42962 ds920p_64551 ds1520p_42962 sa3600_64551 ds918p_42218 rs3621xsp_42962 ds720p_42962 ds1019p_42962 ds1621xsp_42218 ds3615xs_64551 sa3400_64551 rs3413xsp_42962 ds3615xs_42218 ds1621p_42962 dva3221_64551 fs2500_42218
[#] =======================================================================================

Updating extension : all-modules contents for model : ds3622xsp_64551
[#] Checking runtime for required tools... [OK]
[#] Updating ds3622xsp_64551 platforms extensions...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/all-modules/releases/broadwellnk.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Filling-in newly downloaded recipe for extension all-modules platform ds3622xsp_64551
[#] Downloading remote file https://github.com/pocopico/redpill-modules/releases/latest/download/broadwellnk-4.4.180.tgz to /home/tc/redpill-load/custom/extensions/all-modules/ds3622xsp_64551/broadwellnk-4.4.180.tgz
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/all-modules/ds3622xsp_64551/broadwellnk-4.4.180.tgz file...  [ERR]
[!] Checksum mismatch - expected d9b748d1de74c09a0a3edc0a6f83813399492c3a50564cca90d8c0368ba5340f but computed 4568b83f989d89c8da06bcc27a5f1fdc4c8e81c05bca30a9605e22654045ff88

*** Process will exit ***
Updating extension : eudev contents for model : ds3622xsp_64551
[#] Checking runtime for required tools... [OK]
[#] Updating ds3622xsp_64551 platforms extensions...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/eudev/recipes/universal.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Filling-in newly downloaded recipe for extension eudev platform ds3622xsp_64551
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/master/eudev/releases/eudev.tgz to /home/tc/redpill-load/custom/extensions/eudev/ds3622xsp_64551/eudev.tgz
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/eudev/ds3622xsp_64551/eudev.tgz file...  [OK]
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/master/eudev/releases/install.sh to /home/tc/redpill-load/custom/extensions/eudev/ds3622xsp_64551/install.sh
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/eudev/ds3622xsp_64551/install.sh file...  [OK]
[#] Successfully processed recipe for extension eudev platform ds3622xsp_64551
[#] Verifying /home/tc/redpill-load/custom/extensions/eudev/ds3622xsp_64551/install.sh file...  [OK]
Updating extension : disks contents for model : ds3622xsp_64551
[#] Checking runtime for required tools... [OK]
[#] Updating ds3622xsp_64551 platforms extensions...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/disks/recipes/universal.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Filling-in newly downloaded recipe for extension disks platform ds3622xsp_64551
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/disks/releases/dtc to /home/tc/redpill-load/custom/extensions/disks/ds3622xsp_64551/dtc
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/disks/ds3622xsp_64551/dtc file...  [OK]
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/disks/releases/install.sh to /home/tc/redpill-load/custom/extensions/disks/ds3622xsp_64551/install.sh
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/disks/ds3622xsp_64551/install.sh file...  [ERR]
[!] Checksum mismatch - expected d37cf99cdb543c2598477193f149506db0a6f9f7f17357b7fc15c67dd0354c2a but computed 7590d9c09eb3a548ee9a838bac70d800f38582372377d9651221fb1e570f912b

*** Process will exit ***
Updating extension : misc contents for model : ds3622xsp_64551
[#] Checking runtime for required tools... [OK]
[#] Updating ds3622xsp_64551 platforms extensions...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/misc/recipes/universal.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Filling-in newly downloaded recipe for extension misc platform ds3622xsp_64551
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/master/misc/releases/install-all.sh to /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/install-all.sh
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/install-all.sh file...  [OK]
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/master/misc/releases/ttyd.tar.gz to /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/ttyd.tar.gz
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/ttyd.tar.gz file...  [OK]
[#] Unpacking files from /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/ttyd.tar.gz to /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/...  [OK]
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/master/misc/releases/install_rd.sh to /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/install_rd.sh
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/install_rd.sh file...  [OK]
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/master/misc/releases/lrzsz.tar.gz to /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/lrzsz.tar.gz
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/lrzsz.tar.gz file...  [OK]
[#] Unpacking files from /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/lrzsz.tar.gz to /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/...  [OK]
[#] Successfully processed recipe for extension misc platform ds3622xsp_64551
[#] Unpacking files from /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/lrzsz.tar.gz to /home/tc/redpill-load/custom/extensions/misc/ds3622xsp_64551/...  [OK]
[#] Checking runtime for required tools... [OK]
[#] Updating extensions...

[#] Checking runtime for required tools... [OK]
[#] Adding new extension from https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json...
[#] Downloading remote file https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%
[OK]
[#] ========================================== redpill-boot-wait ==========================================
[#] Extension name: RedPill Bootwait
[#] Description: Simple extension which stops the execution early waiting for the boot device to appear
[#] To get help visit: https://github.com/pocopico/rp-ext/redpill-boot-wait
[#] Extension preparer/packer: https://github.com/pocopico/rp-ext/tree/main/redpill-boot-wait
[#] Update URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill-boot-wait/rpext-index.json
[#] Platforms supported: ds1621p_42218 ds1621p_42951 ds918p_41890 dva3221_42661 ds3617xs_42621 ds3617xs_42218 ds920p_42661 dva3221_42962 ds918p_42661 ds3622xsp_42962 ds3617xs_42951 ds920p_42962 ds1621p_42661 ds923p_42962 dva1622_42951 ds918p_25556 dva3221_42218 ds3615xs_42661 dva3221_42951 ds3622xsp_42661 ds2422p_42661 ds3622xsp_42218 ds2422p_42962 rs4021xsp_42621 dva1622_42962 ds2422p_42218 rs4021xsp_42962 dva3221_42621 ds3615xs_42962 ds3617xs_42962 ds3615xs_41222 ds920p_42951 rs4021xsp_42218 ds2422p_42951 ds918p_42621 ds3617xs_42661 ds3615xs_25556 ds920p_42218 rs4021xsp_42951 ds920p_42621 ds918p_42962 ds3615xs_42951 ds3622xsp_42951 ds920p_42550 dva1622_42661 ds918p_42218 ds2422p_42621 ds1621p_42621 ds3615xs_42621 ds3615xs_42218 ds1621p_42962 ds3622xsp_42621 rs4021xsp_42661
[#] =======================================================================================

[#] Checking runtime for required tools... [OK]
[#] Updating all-modules extension...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/all-modules/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Extension all-modules index is already up to date
[#] Updating disks extension...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/disks/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Extension disks index is already up to date
[#] Updating eudev extension...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/eudev/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Extension eudev index is already up to date
[#] Updating misc extension...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/misc/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Extension misc index is already up to date
[#] Updating pocopico.vmxnet3 extension...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/rp-ext/master/vmxnet3/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Extension pocopico.vmxnet3 index is already up to date
[#] Updating redpill-boot-wait extension...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill-boot-wait/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Extension redpill-boot-wait index is already up to date
[#] Updating redpill-boot-wait extension... [OK]
[#] Checking runtime for required tools... [OK]
[#] Updating ds3622xsp_64551 platforms extensions...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/all-modules/releases/broadwellnk.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
###################################################################################################################################################################################################################################### 100.0%

[#] Extension all-modules for ds3622xsp_64551 platform is already up to date
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/disks/recipes/universal.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
###################################################################################################################################################################################################################################### 100.0%
[#] Extension disks for ds3622xsp_64551 platform is already up to date
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/eudev/recipes/universal.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
###################################################################################################################################################################################################################################### 100.0%
[#] Extension eudev for ds3622xsp_64551 platform is already up to date
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/misc/recipes/universal.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
###################################################################################################################################################################################################################################### 100.0%
[#] Extension misc for ds3622xsp_64551 platform is already up to date
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/rp-ext/master/vmxnet3/releases/ds3622xsp_64216.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
###################################################################################################################################################################################################################################### 100.0%
[#] Filling-in newly downloaded recipe for extension pocopico.vmxnet3 platform ds3622xsp_64551
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/rp-ext/master/vmxnet3/releases/vmxnet3-4.4.302plus-broadwellnk.tgz to /home/tc/redpill-load/custom/extensions/pocopico.vmxnet3/ds3622xsp_64551/vmxnet3-4.4.302plus-broadwellnk.tgz
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/pocopico.vmxnet3/ds3622xsp_64551/vmxnet3-4.4.302plus-broadwellnk.tgz file... [OK]
[#] Unpacking files from /home/tc/redpill-load/custom/extensions/pocopico.vmxnet3/ds3622xsp_64551/vmxnet3-4.4.302plus-broadwellnk.tgz to /home/tc/redpill-load/custom/extensions/pocopico.vmxnet3/ds3622xsp_64551/... [OK]
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/rp-ext/master/vmxnet3/src/check-vmxnet3.sh to /home/tc/redpill-load/custom/extensions/pocopico.vmxnet3/ds3622xsp_64551/check-vmxnet3.sh
###################################################################################################################################################################################################################################### 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/pocopico.vmxnet3/ds3622xsp_64551/check-vmxnet3.sh file... [OK]
[#] Successfully processed recipe for extension pocopico.vmxnet3 platform ds3622xsp_64551
[-] The extension redpill-boot-wait was found. However, the extension index has no recipe for ds3622xsp_64551 platform. It may not be
[-] supported on that platform, or author didn't updated it for that platform yet. You can try running
[-] "ext-manager.sh update" to refresh indexes for all extensions manually. Below are the currently known information about
[-] the extension stored locally:
[#] ========================================== redpill-boot-wait ==========================================
[#] Extension name: RedPill Bootwait
[#] Description: Simple extension which stops the execution early waiting for the boot device to appear
[#] To get help visit: https://github.com/pocopico/rp-ext/redpill-boot-wait
[#] Extension preparer/packer: https://github.com/pocopico/rp-ext/tree/main/redpill-boot-wait
[#] Update URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill-boot-wait/rpext-index.json
[#] Platforms supported: ds1621p_42218 ds1621p_42951 ds918p_41890 dva3221_42661 ds3617xs_42621 ds3617xs_42218 ds920p_42661 dva3221_42962 ds918p_42661 ds3622xsp_42962 ds3617xs_42951 ds920p_42962 ds1621p_42661 ds923p_42962 dva1622_42951 ds918p_25556 dva3221_42218 ds3615xs_42661 dva3221_42951 ds3622xsp_42661 ds2422p_42661 ds3622xsp_42218 ds2422p_42962 rs4021xsp_42621 dva1622_42962 ds2422p_42218 rs4021xsp_42962 dva3221_42621 ds3615xs_42962 ds3617xs_42962 ds3615xs_41222 ds920p_42951 rs4021xsp_42218 ds2422p_42951 ds918p_42621 ds3617xs_42661 ds3615xs_25556 ds920p_42218 rs4021xsp_42951 ds920p_42621 ds918p_42962 ds3615xs_42951 ds3622xsp_42951 ds920p_42550 dva1622_42661 ds918p_42218 ds2422p_42621 ds1621p_42621 ds3615xs_42621 ds3615xs_42218 ds1621p_42962 ds3622xsp_42621 rs4021xsp_42661
[#] =======================================================================================

[-] Failed to update recipe for redpill-boot-wait extension for platform ds3622xsp_64551. The script will terminate as you do not
[-] have previously downloaded recipe which can be used if download fails. Try again later. If problem
[-] persists contact the extension packer for support (displayed below)
[#] ========================================== redpill-boot-wait ==========================================
[#] Extension name: RedPill Bootwait
[#] Description: Simple extension which stops the execution early waiting for the boot device to appear
[#] To get help visit: https://github.com/pocopico/rp-ext/redpill-boot-wait
[#] Extension preparer/packer: https://github.com/pocopico/rp-ext/tree/main/redpill-boot-wait
[#] Update URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill-boot-wait/rpext-index.json
[#] Platforms supported: ds1621p_42218 ds1621p_42951 ds918p_41890 dva3221_42661 ds3617xs_42621 ds3617xs_42218 ds920p_42661 dva3221_42962 ds918p_42661 ds3622xsp_42962 ds3617xs_42951 ds920p_42962 ds1621p_42661 ds923p_42962 dva1622_42951 ds918p_25556 dva3221_42218 ds3615xs_42661 dva3221_42951 ds3622xsp_42661 ds2422p_42661 ds3622xsp_42218 ds2422p_42962 rs4021xsp_42621 dva1622_42962 ds2422p_42218 rs4021xsp_42962 dva3221_42621 ds3615xs_42962 ds3617xs_42962 ds3615xs_41222 ds920p_42951 rs4021xsp_42218 ds2422p_42951 ds918p_42621 ds3617xs_42661 ds3615xs_25556 ds920p_42218 rs4021xsp_42951 ds920p_42621 ds918p_42962 ds3615xs_42951 ds3622xsp_42951 ds920p_42550 dva1622_42661 ds918p_42218 ds2422p_42621 ds1621p_42621 ds3615xs_42621 ds3615xs_42218 ds1621p_42962 ds3622xsp_42621 rs4021xsp_42661
[#] =======================================================================================

[!] Cannot continue due to previous errors (see above)

*** Process will exit ***
[!] Failed to update all extensions for ds3622xsp_64551 platform - see errors above

*** Process will exit ***
FAILED : Loader creation failed check the output for any errors

**Comment by pocopico** [comment]
Can you try the following : 

 - Download latest image
 - Once booted, use a web browser to access the IP of TCRP e.g http://XX.XX.XX.XX/index.html
 - Select Model and Version
 - On build form check variables 
 - Click build

**Comment by pocopico** [comment]
Fixed on latest release
