### ISSUE TITLE
Installation hangs 99% 

### ISSUE THREAD

**Issue by sojab0on** [pocopico/tinycore-redpill#268]
Hi i tried to build the loader trough the steps all went fine after booting to the usb option it fails 
to install the .pat from synology 

After some thinkering with ds3617xs witch did not want to install 

I recreated a usb drive with ds3622xs+ bootloader works fine even the setup process goes on but it hangs at 99% 
Used the 7.1.1-42962 setup and downloaded de DSM_DS3622xs+_42962.pat from synology 

it uploads fine and insatall goes trough to 99% and just sits there

**Comment by sojab0on** [comment]
Tried to get the patched pat from tinycore but from any location when i try scp or ptty sftp it blocks the transfer

**Comment by GunterO** [comment]
I had the same problem with DS3622xs+ 7.2.0-64551. Switched to DS920+ and now it is installing just fine.
Maybe because my bare metal machine is an i7 and not a XEON cpu?

**Comment by lzzsalvo** [comment]
I encountered the same problem using the latest version available on 05/21/2023. I tried installing both DSM7.1.1 and DSM7.2. The installation hangs at 99%.
![DSM7 2 Virtual Synology](https://github.com/pocopico/tinycore-redpill/assets/95186977/b9bd9dc6-901e-4d48-8d81-f3cd856bb7ab)

**Comment by pocopico** [comment]
If you had your DSM connected to internet then there must be something that still needs to be fixed. Did you use HTML air CLI for the loader creation ?

**Comment by lzzsalvo** [comment]
> If you had your DSM connected to internet then there must be something that still needs to be fixed. Did you use HTML air CLI for the loader creation ?

The DSM was connected to the internet and I used the HTML CLI to create the loader.
Is there likely something wrong with the creation of the partition at the end of the process?

**Comment by pocopico** [comment]
No, i haven’t yet figured out why this is happening, the installer tries to fetch some updates from the internet and it hangs there waiting for something.

**Comment by lzzsalvo** [comment]
> No, i haven’t yet figured out why this is happening, the installer tries to fetch some updates from the internet and it hangs there waiting for something.

This is what I can see from the proxmox terminal during installation. DS3622xs+ freezes at 99%.

![2](https://github.com/pocopico/tinycore-redpill/assets/95186977/954c51b6-1f6c-48af-983e-facbc9024572)
![3](https://github.com/pocopico/tinycore-redpill/assets/95186977/f434fceb-b791-4224-83a4-072131b358d3)
![4](https://github.com/pocopico/tinycore-redpill/assets/95186977/7cd5ad95-7e33-4d53-b57f-d4904d7d256a)
![Immagine 2023-05-21 164233](https://github.com/pocopico/tinycore-redpill/assets/95186977/4cadaf2f-bbc8-4402-99f9-423aad2e99eb)

**Comment by sojab0on** [comment]
As fas as i can tell it made a ext4 partition with ext4-fs and it tries to mount it as a ext3 witch it cant becaue there is a fundamental diffence between ext 3 and 4 in features .

i have yet to check what is does on bare metal

**Comment by lzzsalvo** [comment]
I add more information:
I ran several tests with other models:
DS923+ DSM7.2 installation complete
DS2422+ DSM7.2 installation complete
DS3622xs+ DSM7.2 installation stuck at 99%.
All tests were performed with the same hardware.

**Comment by pocopico** [comment]
The issue is caused somehow with the disks addon. I need to assess further the situation and i'll come back

**Comment by pocopico** [comment]
> I add more information: I ran several tests with other models: DS923+ DSM7.2 installation complete DS2422+ DSM7.2 installation complete DS3622xs+ DSM7.2 installation stuck at 99%. All tests were performed with the same hardware.

Please download latest image, and retry installation of DS3622xs+ 7.2.0. Dont just update the contents, download the new image as the problem is on the image itself

**Comment by lzzsalvo** [comment]
> > I add more information: I ran several tests with other models: DS923+ DSM7.2 installation complete DS2422+ DSM7.2 installation complete DS3622xs+ DSM7.2 installation stuck at 99%. All tests were performed with the same hardware.
> 
> Please download latest image, and retry installation of DS3622xs+ 7.2.0. Dont just update the contents, download the new image as the problem is on the image itself

I've tested with the latest image release. I confirm that the installation on DS3622xs+ is successful. Thank you very much

**Comment by pocopico** [comment]
> The issue is caused somehow with the disks addon. I need to assess further the situation and i'll come back

So the problem with disks addon can be easily solved. Pushing the update.

**Comment by sojab0on** [comment]
With new loader file it constantly crashes on building a loader tried 
DS3615xs 3617xs and cd standard one it uses 3622xsp 

Trough web version and cli/ssh 

on the ds3622xsp this is the last output from ssh/cli 
################################################################################################################# 100.0%
[#] Verifying /home/tc/redpill-load/custom/extensions/thethorgroup.boot-wait/ds3622xsp_64561/boot-wait.sh file... [OK]
[#] Successfully processed recipe for extension thethorgroup.boot-wait platform ds3622xsp_64561
[#] Verifying /home/tc/redpill-load/custom/extensions/thethorgroup.boot-wait/ds3622xsp_64561/boot-wait.sh file... [OK]
[#] Updating extensions... [OK]
[#] Verifying /home/tc/redpill-load/cache/ds3622xsp_64561.pat file... [OK]
[#] Unpacking /home/tc/redpill-load/cache/ds3622xsp_64561.pat file to /home/tc/redpill-load/build/1685011882/pat-ds3622xsp_64561-unpacked... [OK]
[#] Verifying /home/tc/redpill-load/build/1685011882/pat-ds3622xsp_64561-unpacked/zImage file... [OK]
[#] Patching /home/tc/redpill-load/build/1685011882/pat-ds3622xsp_64561-unpacked/zImage to /home/tc/redpill-load/build/1685011882/zImage-patched... [OK]
[#] Verifying /home/tc/redpill-load/build/1685011882/pat-ds3622xsp_64561-unpacked/rd.gz file... [OK]
[#] Unpacking /home/tc/redpill-load/build/1685011882/pat-ds3622xsp_64561-unpacked/rd.gz file to /home/tc/redpill-load/build/1685011882/rd-ds3622xsp_64561-unpacked... [OK]
[#] Apply patches to /home/tc/redpill-load/build/1685011882/rd-ds3622xsp_64561-unpacked... [OK]
[#] Patching config files in ramdisk... [OK]
[#] Adding OS config patching... [OK]
[#] Repacking ramdisk to /home/tc/redpill-load/build/1685011882/rd-patched-ds3622xsp_64561.gz... [OK]
[#] Bundling extensions... [#] Checking runtime for required tools... [OK]
[#] Dumping ds3622xsp_64561 platform extensions to /home/tc/redpill-load/build/1685011882/custom-initrd/exts... [OK]
[#] Packing custom ramdisk layer to /home/tc/redpill-load/build/1685011882/custom.gz... [OK]
[#] Generating GRUB config... include/boot-image.sh: line 148: extra_cmdline['sn']: unbound variable

DS3615xs and 3617xs wont even go trough in web builder they start in the build status list you see it go o the ischaced one sits for 2 seconds then it jumps back t the page with the build info and build button
