### ISSUE TITLE
Booting issue with External drive plug in

### ISSUE THREAD

**Issue by tuntin2022** [pocopico/tinycore-redpill#27]
I got it boot just fine if the only USB boot loader in the system.  If I plug another external USB drive + the USB boot loader and restart the system.  It won't boot, I got error file '/zImage' not found.

**Comment by petersiyuan** [comment]
me too.
I used two smart sockets to solve this problem through the scene(Power variation&On or Off). 
Expect to be able to solve it from the kernel. Thank you！

**Comment by pocopico** [comment]
Change USB port. Edit manual grub until you find the right one
