### ISSUE TITLE
 Verifying Erorr (Checksum mismatch)

### ISSUE THREAD

**Issue by teslaweiler** [pocopico/tinycore-redpill#270]
Verifying /home/tc/redpill-load/custom/extensions/all-modules/dva1622_64551/geminilake-4.4.180.tgz file...  [ERR]
[!] Checksum mismatch - expected 7885fe1e51ec62c859d8acffdc8460660023d5a5f6aee42e77d3ae8fef70723d but computed 9b0e00376c3a2dad64cd1e62a15ffeff176167548a475868e95ff4d048b49789

*** Process will exit ***
Updating extension : eudev contents for model : dva1622_64551
[#] Checking runtime for required tools... [OK]

] Verifying /home/tc/redpill-load/custom/extensions/disks/dva1622_64551/install.sh file...  [ERR]
[!] Checksum mismatch - expected d37cf99cdb543c2598477193f149506db0a6f9f7f17357b7fc15c67dd0354c2a but computed 7590d9c09eb3a548ee9a838bac70d800f38582372377d9651221fb1e570f912b

*** Process will exit ***
Updating extension : misc contents for model : dva1622_64551
<img width="488" alt="Screenshot 2023-05-12 201137" src="https://github.com/pocopico/tinycore-redpill/assets/68001202/790ad07d-6189-4fc0-8a20-a8d94eaf10d5">
<img width="487" alt="Screenshot 2023-05-12 201044" src="https://github.com/pocopico/tinycore-redpill/assets/68001202/35439a69-4c04-41d3-ba9d-0d8b16509ef8">

**Comment by xiaojing110** [comment]
918 same error

**Comment by xiaojing110** [comment]
But it can compile

**Comment by neighborpil** [comment]
ds918p-7.0.1-42218
ds918p-7.0.1-42218-JUN
ds920p-7.0.1-42218
ds920p-7.0.1-42218-JUN

Show the same checksum error

**Comment by pocopico** [comment]
Fixed

**Comment by pocopico** [comment]
- Download latest image
- Once booted, use a web browser to access the IP of TCRP e.g http://xx.xx.xx.xx/index.html
- Select Model and Version
- On build form check variables
- Click build
- reboot and check again status

**Comment by namvan** [comment]
Another similar issue with v0.9.4.5

Updating extension : all-modules contents for model : ds918p_42962  
[#] Checking runtime for required tools... [OK]
[#] Updating ds918p_42962 platforms extensions... 
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/all-modules/releases/apollolake.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
################################################################################################################################################################### 100.0%

[#] Filling-in newly downloaded recipe for extension all-modules platform ds918p_42962
[#] Downloading remote file https://github.com/pocopico/redpill-modules/releases/latest/download/apollolake-4.4.180.tgz to /home/tc/redpill-load/custom/extensions/all-modules/ds918p_42962/apollolake-4.4.180.tgz
################################################################################################################################################################### 100.0%
**[#] Verifying /home/tc/redpill-load/custom/extensions/all-modules/ds918p_42962/apollolake-4.4.180.tgz file...  [ERR]
[!] Checksum mismatch - expected 299dfb23cff10d0fc8b0b18b41cac90b4bfe1abaf7489a7fd8293941898b479b but computed edeaf60886f1ce66adc6f205c1099d5bf87a201e80565ea8b9b6ed0948d24bdd**

*** Process will exit ***
Updating extension : eudev contents for model : ds918p_42962  
[#] Checking runtime for required tools... [OK]
[#] Updating ds918p_42962 platforms extensions... 
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/eudev/recipes/universal.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json

**Comment by A30BL** [comment]
> Can you please also try to :
> 
> * Download latest image
> * Once booted, use a web browser to access the IP of TCRP e.g http://xx.xx.xx.xx/index.html
> * Select Model and Version
> * On build form check variables
> * Click build
> * reboot and check again status

```
Clearing log file
File /home/tc/user_config.json looks OK
Building loader for model, DS3622xs+ and software version, 7.1.1-42951
<br>Downloading tools
PATFILE for DS3622xs+_7.1.1-42951 is NOT CACHED
<br>Downloading PAT file ds3622xsp_42951.pat for MODEL=DS3622xs+, Version=7.1.1-42951, SHA256=11f34ae65b13f7feace40e6a7c2399150ef2b4f4eb3a6dcec0be52fca265f151
<br>Error downloaded file is corrupted
<br>Starting build
<br>Buildling loader for DS3622xs+, 7.1.1-42951, with serial number : 2040SQRANM82K and macaddress : 0011321BDCA0
<br>extracommans : 
<br>Could not determine if file ds3622xsp_42951.pat is encrypted or not, maybe corrupted
-rw-r--r-- 1 tc staff 3322 May 17 15:08 ds3622xsp_42951.pat
<br>04
```1

**Comment by Peter-Wuhoo** [comment]
It seems not to fix the issue Checksum mismatch in the latest version:0.9.4.5. I've compiled DS920p many times on esxi and the same errors occurred.

**Comment by pocopico** [comment]
Fixed
