### ISSUE TITLE
DSM 7.1 Beta support

### ISSUE THREAD

**Issue by Zegorax** [pocopico/tinycore-redpill#28]
Hello,

DSM 7.1 has been released as a Beta version. It is available here : https://global.download.synology.com/download/DSM/beta/7.1/42550/DSM_DS3615xs_42550.pat

@pocopico Would it be possible to adapt the loader to this version ?

I tried to perform a manual upgrade using the .pat. After the restart of DSM, it gets stuck and continues to ask to recover over and over.

It is also not possible to install it from scratch. After the first installation of DSM, the system will then reboot and go again to the Recover screen.

**Comment by pocopico** [comment]
The only way to get out of the recovery loop is to telnet to the DSM and remove the /.syno folder. Then perform re-install with old 7.0.1 pat file.

**Comment by Zegorax** [comment]
It was a test VM so I don't really need to recover it (there was nothing on it)
For DSM 7.1, do you mean it is possible to install it if the .syno folder is removed ?

**Comment by pocopico** [comment]
No, currently the upgrade to 7.1 is not possible

**Comment by Zegorax** [comment]
Do you know already the modifications that needs to be made ? If yes, can I help ?

**Comment by pocopico** [comment]
We are still trying to figure out what issues are caused by the new update and the root causes

**Comment by Graid1988** [comment]
Tell me how to delete / .syno via telnet?
Describe in more detail. Thanks

**Comment by rayau85** [comment]
I have the same problem. Take me very long to recover my 7.01.
It is not easy to ssh the DSM, connection refused.
I need to follow the following steps to get connection.1) Disconnect your raid drives
2) Connect spare HDD to SATA port 1
3) Install DSM 7.01 from fresh Redpill loader, create admin user and server name matching live system, DON'T create volume/raid. Update DSM to match your pre-beta version
4) Shutdown, reconnect raid drives to SATA ports 2-n
5) Boot, login, repair system partitions on raid, shutdown

Set ssh server in the DSM

Ssh to dsm

then remove some files with this
rm -rf /SynoUpgradePackages
rm -f /SynoUpgrade.tar
rm -f /SynoUpgradeindex.txz
rm -f /SynoUpgradeSynohdpackImg.txz
rm -f /checksum.syno
rm -f /.syno/patch/*

6) Remove spare HDD and reconnect raid drives to SATA ports 1-n
7) Boot, repair packages etc

Then re-install the DSM 7.01 onto the Raids drive again.
And set up the NAS again.

**Comment by pocopico** [comment]
Fixed since 0.7.0.0
