### ISSUE TITLE
build error : all-modules Checksum mismatch

### ISSUE THREAD

**Issue by damienmillet** [pocopico/tinycore-redpill#283]
### Version
7.2
### Message
all-modules : Checksum mismatch - expected d9b748d1de74c09a0a3edc0a6f83813399492c3a50564cca90d8c0368ba5340f but computed 4568b83f989d89c8da06bcc27a5f1fdc4c8e81c05bca30a9605e22654045ff88
### Solution
-

**Comment by pocopico** [comment]
Fixed checksum, thanks
