### ISSUE TITLE
build error : No space left on device

### ISSUE THREAD

**Issue by damienmillet** [pocopico/tinycore-redpill#284]
### Version
7.2
### Message
cp: error writing 'localdiskp1/custom.gz': No space left on device
cp: error writing 'localdiskp1/rd.gz': No space left on device
cp: error writing 'localdiskp1/zImage': No space left on device
sed: couldn't write 394 items to localdiskp1/boot/grub/sedQT9RIq: No space left on device
sdb3: No adequate space on TCRP loader partition /mnt/sdb3 to cache pat file
### Solution
-

**Comment by pocopico** [comment]
Yes, there was that possibility of filling the 1st partition, so since several versions before, i've moved all files to third partition and missed the custom.gz. The last version should be OK

**Comment by damienmillet** [comment]
really fine
