### ISSUE TITLE
can't boot with html build

### ISSUE THREAD

**Issue by damienmillet** [pocopico/tinycore-redpill#288]
maybe cause pid and vid 'ren't updated ?

**Comment by pocopico** [comment]
Are you trying to build < 7.2 versions ? I had the exact issue, i need to check what is goind wrong.

**Comment by damienmillet** [comment]
I just try to recreated the key and pid, vid,sn, Mac was empty

**Comment by pocopico** [comment]
So nothing has changed with 7.1, you can use ./rploader.sh (though i need to check again cause i changed several stuff).



Until now i've tested most model builds with 7.2 succesfully using the HTML builder.

Its getting kind of late and i'm already burned :-) Tomorrow i'll continue working on builds earlier then 7.2

**Comment by damienmillet** [comment]
ty good night

**Comment by pocopico** [comment]
Late last night i was able to fix some of the HTML issues and got the rploader.sh back into a working state.

Latest image should work (I hope)

**Comment by damienmillet** [comment]
when using web and change Mac address, it isn't added to the user... file
![Capture d’écran 2023-05-16 à 22 10 25](https://github.com/pocopico/tinycore-redpill/assets/12233383/20883d81-30f4-42e6-aca2-3916e4a3534a)

 ### Grub.cfg
![Capture d’écran 2023-05-16 à 22 12 34](https://github.com/pocopico/tinycore-redpill/assets/12233383/aacb4627-e824-4305-ae38-47c67be6625b)
### sda3/user_conf.json
![Capture d’écran 2023-05-16 à 22 13 21](https://github.com/pocopico/tinycore-redpill/assets/12233383/27a08dde-9b4c-45bb-ac69-f559e666ae20)

**Comment by damienmillet** [comment]
### I tried with UTM and a vm with vmxnet3 with 7.2.0-64551 (vmdk used)
- cli build success ✅
- boot on friend ✅ (ping ok)
- boot on dsm ❌ (ping ko)
- boot on usb ❌ (ping ko)
- boot on sata ❌ (ping ko)
>  I don't know if the vmdk ll be used as usb or sata, it should be nice to write if loader is found on device or not.

![Capture d’écran 2023-05-16 à 23 32 52](https://github.com/pocopico/tinycore-redpill/assets/12233383/f5c89fcd-af46-4422-8b18-34d4dd21d960)

even in /mnt/sda3

i thk it was a problem with my Nic but vmxnet3 should work but isn't

**Comment by damienmillet** [comment]
with 7.1.1 work ✅

**Comment by GunterO** [comment]
> html with 7.1.1 work ✅

How? Is returning this error when I try via HTML:
Could not determine if file ds3622xsp_42951.pat is encrypted or not, maybe corrupted

**Comment by GunterO** [comment]
> > html with 7.1.1 work ✅
> 
> How? Is returning this error when I try via HTML: 
Could not determine if file ds3622xsp_42951.pat is encrypted or not, maybe corrupted
I'm trying with the latest 0.9.4.5 build from yesterday evening, 16/5/23 20:24 (Too bad the version number does not increase after each build).

**Comment by damienmillet** [comment]
You can grab it from url in the conf file. Store it in the html folder
