### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by damienmillet** [pocopico/tinycore-redpill#289]
### Version
7.2
### Message
cp: cannot stat 'usr/lib/libcurl.so.4': No such file or directory
Copying usr/lib/libmbedcrypto.so.5 to /mnt/sdb3/auxfiles
cp: cannot stat 'usr/lib/libmbedcrypto.so.5': No such file or directory
Copying usr/lib/libmbedtls.so.13 to /mnt/sdb3/auxfiles
cp: cannot stat 'usr/lib/libmbedtls.so.13': No such file or directory
Copying usr/lib/libmbedx509.so.1 to /mnt/sdb3/auxfiles
cp: cannot stat 'usr/lib/libmbedx509.so.1': No such file or directory
Copying usr/lib/libmsgpackc.so.2 to /mnt/sdb3/auxfiles
cp: cannot stat 'usr/lib/libmsgpackc.so.2': No such file or directory
Copying usr/lib/libsodium.so to /mnt/sdb3/auxfiles
cp: cannot stat 'usr/lib/libsodium.so': No such file or directory
Copying usr/lib/libsynocodesign-ng-virtual-junior-wins.so.7 to /mnt/sdb3/auxfiles
cp: cannot stat 'usr/lib/libsynocodesign-ng-virtual-junior-wins.so.7': No such file or directory
Copying usr/syno/bin/scemd to /mnt/sdb3/auxfiles
cp: cannot stat 'usr/syno/bin/scemd': No such file or directory
Copying required libraries to local lib directory
cp: cannot stat '/mnt/sdb3/auxfiles/extractor/lib*': No such file or directory
Linking lib to lib64
Copying executable
cp: cannot stat '/mnt/sdb3/auxfiles/extractor/scemd': No such file or directory
Removing temp folder /tmp/synoesp
Checking if tools is accessible
./rploader.sh: line 681: /bin/syno_extract_system_patch: No such file or directory
Cound not execute
...
sudo: /bin/syno_extract_system_patch: command not found
...
Checking config file existence -> No config file found, please use the proper repo, clean and download again

### Context 
version : 7.2.0-64551
model : DS3622xs+
on build

**Comment by pocopico** [comment]
I need to verify co-existence of html and rploader ...

**Comment by damienmillet** [comment]
i try that : 

❌  Create key by cli 7.1.1 
❌  Create key by cli 7.2.0
❌  Create key by html 7.1.1
> error #275 
> wait some second then reload the page
> or `wget https://global.download.synology.com/download/DSM/release/7.1.1/42962/DSM_DS3622xs%2B_42962.pat -O ds3622xsp_42951.pat` then reload the page

> key created ⚠️
> works but pid/vid isn't update, maybe don't care
> At usb start, zImage-dsm not found ❌
> At friend start, freeze and crash ❌
> Maybe test unite and functional should be nice in workflows

❌  Create key by html 7.2.0
> reset model
> select DS3622xs+/7.2.0-64551 with realmac
> on realmac click, ask me to select model and loop ⚠️
> version is empty ❌
> reset model ! this bug loop again and again
> I wrote my Mac  then `build` 
> Success ✅
> friend boot should be, so `reboot` and wait
> shutdown ✅
> restart ⚠️ (restart on tcrp when next entry was friend)
> `/tmp/cmdline.check : {mac1,pid,sn,vid} command not found ❌
> they're not in user_conf...

- html is now running at start without upgrade or monitor 👍
- `./rpload.sh update` can only be used manually with `sudo -`
- my best friend is definitively : `sed '/^192\.168\.xx\.xx.*$/d' ~/.ssh/known_hosts | echo > ~/.ssh/known_hosts`

**Comment by pocopico** [comment]
I had to change a lot of staff to get rploader.sh back into working status. I've put all my focus into HTML build tool and this has fallen behind. I think latest image is now in workable condition.

**Comment by damienmillet** [comment]
tested ✅
