### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by trap84** [pocopico/tinycore-redpill#290]
Extracting encrypted pat file : /home/tc/custom-module/ds3622xsp_42962.pat to /tmp/pat
sudo: /bin/syno_extract_system_patch: command not found
extract latest pat
Creating unecrypted pat file ds3622xsp_42962.pat to /home/tc/redpill-load/cache folder
tar: ./VERSION: Not found in archive
tar: Exiting with failure status due to previous errors
Pat file  sha256sum is : 7a339b4f0dd9c32b11d036e6c68ef70dc32eea438513a776f23dc230be889ab7
Checking config file existence -> No config file found, please use the proper repo, clean and download again
tc@box:~$ tar: ./VERSION: Not found in archivesudo: /bin/syno_extract_system_pat
ch: command not found
-sh: tar:: not found

**Comment by damienmillet** [comment]
maybe it's a duplicated #289

**Comment by pocopico** [comment]
> maybe it's a duplicated #289

Yes, working on that
