### ISSUE TITLE
fullupgrade error

### ISSUE THREAD

**Issue by damienmillet** [pocopico/tinycore-redpill#291]
### Contexte
Manual
### Message
Backing up home files to sdb : sed: can't create temp file '/opt/.filetool.lstW4HR6Q': Permission denied
### Bypass with
`echo Y | sudo ./rploader.sh fullupgrade`

**Comment by pocopico** [comment]
it should be fixed on latest image (just now)

**Comment by damienmillet** [comment]
tested ✅
