### ISSUE TITLE
user_config.json file looks corrupted

### ISSUE THREAD

**Issue by damienmillet** [pocopico/tinycore-redpill#294]
### Contexte
on html : 
- reset model to choose 7.2
- set 3622xsp
- set 7.2.0-64551
- click to realmac
### Message
Error both /home/tc/user_config.json file looks corrupted, select Additional Actions -> Reset model to recreate

ps : it should be nice to create a issue model ;)

**Comment by pocopico** [comment]
I have opened the discussions if you like you can be the second user :)

**Comment by damienmillet** [comment]
I talk about a method to write issue to get more information, that can be useful sometime.
Contexte ?
Version ?
Web or Cli ? 
Manual or Auto ?

to help to understand the situation to fix it or explain

**Comment by pocopico** [comment]
Oh yes i get it , that for me to be able to test should then be smg like : 

Build Method (html/cli) : 
Select Model & Version (e.g. DS3622xs 7.1.1 42952) : 
Command issued: 
Result : 
Suggested Fix:

Result:

**Comment by damienmillet** [comment]
yes !! 
take a look: 
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by pocopico** [comment]
I've updated the user_config.json update function and it now looks more stable. Using file to store the changed insted of using a bash variable.

**Comment by damienmillet** [comment]
tested ✅

**Comment by damienmillet** [comment]
I FOUND IT ! 😃
when we reset the model, sometimes the version isn't returned to the request, like :
`http://xx.xx.xx.xx/index.sh?action=build&mymodel=DS3622xs+&myversion=`
then when I ask to use my realmac an error is catch !
> Error both /home/tc/user_config.json file looks corrupted, select Additional Actions -> Reset model to recreate
if I change the url to : 
`http://xx.xx.xx.xx/index.sh?action=build&mymodel=DS3622xs+&myversion=64551`
it's nice 😉

**Comment by damienmillet** [comment]
damned I close it without ur patch to fix haha

**Comment by damienmillet** [comment]
https://github.com/pocopico/tinycore-redpill/assets/12233383/cbfbc1ff-4e76-4795-84e8-a4fc18af5ed2

but when I did it, sometime the model isn't fully written

**Comment by damienmillet** [comment]
ok when I did it, the model haven't + for 3622

**Comment by pocopico** [comment]
The issue was caused by overlapping user_config json updated, implemented a wait mechanism for each value to be applied.
