### ISSUE TITLE
Loader creation fails, missing dpkg?

### ISSUE THREAD

**Issue by sonoseco** [pocopico/tinycore-redpill#3]
When building the loader and starts checking for extensions, it fails with error: `Some tools weren't available - install them first`
Here's a screenshot.

Any ideas?
Thanks
![IMG_0939](https://user-images.githubusercontent.com/9100014/149345761-e2bbb0ec-7a28-4759-81a3-29ac5d81cd1f.jpeg)
.

**Comment by pocopico** [comment]
You need to edit manually redpill-load/include/runtime.sh 
 
And comment the line by adding a # in front of the line.
 
#[dpkg]="dpkg --version" # extract flashupdate

**Comment by xiaoyaoz1** [comment]
同样遇到了Some tools weren't available - install them first
