### ISSUE TITLE
After upload "DSM_DS3622xs+_64551.pat" looping at Welcome screen

### ISSUE THREAD

**Issue by Pascalleung** [pocopico/tinycore-redpill#300]
After upload "DSM_DS3622xs+_64551.pat" looping at Welcome screen

create USB stick by tinycore-redpill-uefi.v0.9.4.5.img
boot redpill
./rploader.sh update
./rploader.sh fullupgrade
./rploader.sh identifyusb
./rploader.sh satamap
./rploader.sh serialgen DS3622xs+
./rploader.sh build ds3622xsp-7.2.0-64551
filetool.sh -b
exitcheck.sh reboot

it can access by browser and upload DSM_DS3622xs+_64551.pat and ask for hardisk erase
but it will looping at upload DSM_DS3622xs+_64551.pat again
![image](https://github.com/pocopico/tinycore-redpill/assets/113500437/e6006491-3ba8-4631-8668-09c6829b65fd)
 is it some idea to fix it ? many thanks.

**Comment by liuxiang91** [comment]
same here

**Comment by dantesia** [comment]
Same, but on 918+

**Comment by lzzsalvo** [comment]
same here

**Comment by jsanchez-98** [comment]
I haven't downloaded the "DSM_DS3622xs+_64551.pat" and clicking on the first option also throws an error and starts the process again. If this DSM doesn't work, is there any other stable one?

**Comment by xiaojing110** [comment]
Same, but on 918+too

**Comment by pocopico** [comment]
Are you using the cached file or the one downloaded from syno ?

**Comment by Pascalleung** [comment]
Hi pocopico, I don't know where the cached file. So i download the PAT from syco website.
![ds3622](https://github.com/pocopico/tinycore-redpill/assets/113500437/dfc93c89-5a22-4f37-871f-fb63d8b539db)

**Comment by pocopico** [comment]
hm then that means that i need to test more :)

**Comment by teslaweiler** [comment]
same here on 1622

**Comment by Pascalleung** [comment]
Hi pocopico, I am very appreciate with your passion. may be the issue was 7.2 RC
it look like cannot write the DSM to USB stick ; so it asking and asking.
many thanks.

**Comment by yyxida** [comment]
It doesn't seem like a 7.2rc issue. I installed 7.1.1 and 7.1.0 for 3617 and 3622 respectively, and both will have this welcome page loop (uploading pat files offline from the network).
Unable to test Jun mod for 7.0.1 because it cannot be compiled.

**Comment by pocopico** [comment]
can you please try to redownload the latest release and use HTML to build the loader ?

**Comment by Pascalleung** [comment]
Hi Pocopico, I saw the file name still was " tinycore-redpill-uefi.v0.9.4.5.img " ; is it had new content compare with few day ago ?
and I am not understand was mean of " use HTML to build the loader " .
Because i just knew write the IMG file to USB stick > bootup > at TC console to key-in command step-by-step to create the DSM.
Thanks.

**Comment by lzzsalvo** [comment]
I encountered a hang while installing using the latest version available on 05/21/2023. I tried installing both DSM7.1.1 and DSM7.2. The installation hangs at 99%.
![DSM7 2 Virtual Synology](https://github.com/pocopico/tinycore-redpill/assets/95186977/9ee3eba3-6fdf-43b5-85d5-cf791007af05)

**Comment by dantesia** [comment]
lzzsalvo - same 
cpu and disk ~ from 50% install show, that load = 0%

**Comment by dantesia** [comment]
and one more, when try 7.2

Found SCSI Controller : pciid 1000d00000030  Required Extension : mptspi
Searching for matching extension for mptspi
Found matching extension : 
https://raw.githubusercontent.com/pocopico/rp-ext/master/mptspi/rpext-index.json
Adding extension 
**Extension does not contain information about platform ds918p_64551**
Found SATA Controller : pciid 15add000007e0  Required Extension : 
No matching extension
Found Ethernet Interface : pciid 8086d000010d3 Required Extension : e1000e
Searching for matching extension for e1000e
Found matching extension : 
https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json
Adding extension 
**Extension does not contain information about platform ds918p_64551**

need to make new:
"ds918p_64551": "https://raw.githubusercontent.com/pocopico/rp-ext/master/mptspi/releases/ds918p_64551.json",
and
"ds918p_64551": "https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/releases/ds918p_64551.json",

tnx for all your work!

**Comment by pocopico** [comment]
OK, i found the reason for 99% stuck and i think i've fixed that.

Download latest image and burn again. Do not just update, Its a problem in the image itself.

**Comment by lzzsalvo** [comment]
> OK, i found the reason for 99% stuck and i think i've fixed that.
> 
> Download latest image and burn again. Do not just update, Its a problem in the image itself.

I just finished testing the latest image release and the installation of DSM7.2 on DS3622xs+ was successful.
Thanks a lot for your support.

![1](https://github.com/pocopico/tinycore-redpill/assets/95186977/de7def07-32f0-4075-b890-fad9107f57dd)

**Comment by pocopico** [comment]
Super, need few more feedbacks then before I close this

**Comment by Pascalleung** [comment]
@pocopico , using updated V0.9.4.5 and build again. it working fine.
![image](https://github.com/pocopico/tinycore-redpill/assets/113500437/0c8c0f2b-50c8-4b8e-9c2d-0db0253658ad)

**Comment by pocopico** [comment]
Thank you Gentlemans, closing as fixed !
