### ISSUE TITLE
ds3615xs_42962 bromolow-3.10.108.tgz  Not Found 

### ISSUE THREAD

**Issue by hassbian-ABC** [pocopico/tinycore-redpill#302]
curl: (22) The requested URL returned error: 404 Not Found                     

[-] Recipe file for extension all-modules platform ds3615xs_42962 is logically invalid - failed to download file https://github.com/pocopico/redpill-modules/releases/latest/download/bromolow-3.10.108.tgz. You SHOULD contact the extension packer to report that (see below)

**Comment by pocopico** [comment]
Fixed
