### ISSUE TITLE
Installing 7.1 and 7.1.1 will result in an infinite loop of welcome pages

### ISSUE THREAD

**Issue by yyxida** [pocopico/tinycore-redpill#303]
I installed 7.1.1 and 7.1.0 for 3617 and 3622 respectively, and both will have this welcome page loop (uploading pat files offline from the internet).
Unable to test Jun mod for 7.0.1 because it cannot be compiled.

Entering the shell through the serial port, the data disk has been formatted normally.
I have tried to compile a virtual machine with the same model and version as the one currently running (the version compiled a year ago, version 7.1-42661, 3617), which is also the same loop.
Uploading and installing the Pat file downloaded from Synology
The internet was turned off during the entire installation process, so it should not be an issue with automatic networking updates.

Version: 0.9.4.5
DSM version: 7.1-42661&7.1.1-42962
Model: 3617&3622
Environment: esxi
Virtual machine configuration: Two Sata controllers, with boot disk on port 0 of controller 0 (0:0) and data disk on port 0 of controller 1 (1:0)
satamap：22
Port map: 0200
Maxsata: 2 (shielded boot disk)

Using the CLI：
./rploader.sh update
./rploader.sh fullupgrade
（Manually modifying satamap）
./rploader.sh ext  [DS3622/3617] auto （e1000e and VMXNET3）
./rploader.sh serialgen [DS3622/3617]
./rploader.sh build [ds3622/ds3617/-42661/-42661]
sudo poweroff

**Comment by pocopico** [comment]
can you please try to redownload the latest release and use HTML to build the loader ?

**Comment by pocopico** [comment]
OK, i found the reason for 99% stuck and i think i've fixed that.

**Comment by yyxida** [comment]
Thank you very much, I need to go to the workplace tomorrow for testing.
Regarding HTML, I have some difficulties using it because I am located in China and it will be difficult to access resources on GitHub without configuring proxy.So I can still only use shell for compilation，sry。

**Comment by yyxida** [comment]
Cli cannot compile and will prompt that the file cannot be found. So I tried to compile using cli, but after the failure (expected, but the file was cached) and then compiled using HTML, I got the following error.
`[    1.073159] pci_bus 0000:08: resource 2 [mem 0xf9900000-0xf99fffff 64bit pref]
[    1.074159] pci_bus 0000:09: resource 1 [mem 0xfe100000-0xfe1fffff]
[    1.075160] pci_bus 0000:09: resource 2 [mem 0xf9800000-0xf98fffff 64bit pref]
[    1.076161] pci_bus 0000:0a: resource 1 [mem 0xfe000000-0xfe0fffff]
[    1.077163] pci_bus 0000:0a: resource 2 [mem 0xf9700000-0xf97fffff 64bit pref]
[    1.078164] pci_bus 0000:0b: resource 1 [mem 0xfdf00000-0xfdffffff]
[    1.079164] pci_bus 0000:0b: resource 2 [mem 0xf9600000-0xf96fffff 64bit pref]
[    1.080164] pci_bus 0000:0c: resource 1 [mem 0xfde00000-0xfdefffff]
[    1.081165] pci_bus 0000:0c: resource 2 [mem 0xf9500000-0xf95fffff 64bit pref]
[    1.082164] pci_bus 0000:0d: resource 1 [mem 0xfdd00000-0xfddfffff]
[    1.083164] pci_bus 0000:0d: resource 2 [mem 0xf9400000-0xf94fffff 64bit pref]
[    1.084166] pci_bus 0000:0e: resource 1 [mem 0xfdc00000-0xfdcfffff]
[    1.085170] pci_bus 0000:0e: resource 2 [mem 0xf9300000-0xf93fffff 64bit pref]
[    1.086165] pci_bus 0000:0f: resource 1 [mem 0xfdb00000-0xfdbfffff]
[    1.087168] pci_bus 0000:0f: resource 2 [mem 0xf9200000-0xf92fffff 64bit pref]
[    1.088167] pci_bus 0000:10: resource 1 [mem 0xfda00000-0xfdafffff]
[    1.089167] pci_bus 0000:10: resource 2 [mem 0xf9100000-0xf91fffff 64bit pref]
[    1.090169] pci_bus 0000:11: resource 1 [mem 0xfd900000-0xfd9fffff]
[    1.091168] pci_bus 0000:11: resource 2 [mem 0xf9000000-0xf90fffff 64bit pref]
[    1.092168] pci_bus 0000:12: resource 1 [mem 0xfd800000-0xfd8fffff]
[    1.093170] pci_bus 0000:12: resource 2 [mem 0xf8f00000-0xf8ffffff 64bit pref]
[    1.094173] pci_bus 0000:13: resource 1 [mem 0xfd700000-0xfd7fffff]
[    1.095174] pci_bus 0000:13: resource 2 [mem 0xf8e00000-0xf8efffff 64bit pref]
[    1.096175] pci_bus 0000:14: resource 0 [io  0xf000-0xffff]
[    1.097173] pci_bus 0000:14: resource 1 [mem 0xfd600000-0xfd6fffff]
[    1.098171] pci_bus 0000:14: resource 2 [mem 0xf8d00000-0xf8dfffff 64bit pref]
[    1.099174] pci_bus 0000:15: resource 0 [io  0xe000-0xefff]
[    1.100175] pci_bus 0000:15: resource 1 [mem 0xfd500000-0xfd5fffff]
[    1.101179] pci_bus 0000:15: resource 2 [mem 0xf8c00000-0xf8cfffff 64bit pref]
[    1.102181] pci_bus 0000:16: resource 0 [io  0xd000-0xdfff]
[    1.103175] pci_bus 0000:16: resource 1 [mem 0xfd400000-0xfd4fffff]
[    1.104176] pci_bus 0000:16: resource 2 [mem 0xf8b00000-0xf8bfffff 64bit pref]
[    1.105178] pci_bus 0000:17: resource 0 [io  0xc000-0xcfff]
[    1.106179] pci_bus 0000:17: resource 1 [mem 0xfd300000-0xfd3fffff]
[    1.107176] pci_bus 0000:17: resource 2 [mem 0xf8a00000-0xf8afffff 64bit pref]
[    1.108179] pci_bus 0000:18: resource 0 [io  0xb000-0xbfff]
[    1.109180] pci_bus 0000:18: resource 1 [mem 0xfd200000-0xfd2fffff]
[    1.110179] pci_bus 0000:18: resource 2 [mem 0xf8900000-0xf89fffff 64bit pref]
[    1.111188] pci_bus 0000:19: resource 0 [io  0xa000-0xafff]
[    1.112157] pci_bus 0000:19: resource 1 [mem 0xfd100000-0xfd1fffff]
[    1.113181] pci_bus 0000:19: resource 2 [mem 0xf8800000-0xf88fffff 64bit pref]
[    1.114186] pci_bus 0000:1a: resource 0 [io  0x9000-0x9fff]
[    1.115187] pci_bus 0000:1a: resource 1 [mem 0xfd000000-0xfd0fffff]
[    1.116183] pci_bus 0000:1a: resource 2 [mem 0xf8700000-0xf87fffff 64bit pref]
[    1.117185] pci_bus 0000:1b: resource 0 [io  0x8000-0x8fff]
[    1.118184] pci_bus 0000:1b: resource 1 [mem 0xfcf00000-0xfcffffff]
[    1.119186] pci_bus 0000:1b: resource 2 [mem 0xf8600000-0xf86fffff 64bit pref]
[    1.120190] pci_bus 0000:1c: resource 0 [io  0x7000-0x7fff]
[    1.121188] pci_bus 0000:1c: resource 1 [mem 0xfce00000-0xfcefffff]
[    1.122189] pci_bus 0000:1c: resource 2 [mem 0xf8500000-0xf85fffff 64bit pref]
[    1.123188] pci_bus 0000:1d: resource 0 [io  0x6000-0x6fff]
[    1.124188] pci_bus 0000:1d: resource 1 [mem 0xfcd00000-0xfcdfffff]
[    1.125189] pci_bus 0000:1d: resource 2 [mem 0xf8400000-0xf84fffff 64bit pref]
[    1.126189] pci_bus 0000:1e: resource 0 [io  0x4000-0x4fff]
[    1.127194] pci_bus 0000:1e: resource 1 [mem 0xfcc00000-0xfccfffff]
[    1.128193] pci_bus 0000:1e: resource 2 [mem 0xf8300000-0xf83fffff 64bit pref]
[    1.129190] pci_bus 0000:1f: resource 0 [io  0x3000-0x3fff]
[    1.130191] pci_bus 0000:1f: resource 1 [mem 0xfcb00000-0xfcbfffff]
[    1.131194] pci_bus 0000:1f: resource 2 [mem 0xf8200000-0xf82fffff 64bit pref]
[    1.132193] pci_bus 0000:20: resource 0 [io  0x2000-0x2fff]
[    1.133194] pci_bus 0000:20: resource 1 [mem 0xfca00000-0xfcafffff]
[    1.134194] pci_bus 0000:20: resource 2 [mem 0xf8100000-0xf81fffff 64bit pref]
[    1.135197] pci_bus 0000:21: resource 0 [io  0x1000-0x1fff]
[    1.136196] pci_bus 0000:21: resource 1 [mem 0xfc900000-0xfc9fffff]
[    1.137195] pci_bus 0000:21: resource 2 [mem 0xf8000000-0xf80fffff 64bit pref]
[    1.138201] pci 0000:22:00.0: BAR 6: assigned [mem 0xfbb00000-0xfbb0ffff pref]
[    1.139197] pci 0000:22:01.0: BAR 6: assigned [mem 0xfbb10000-0xfbb1ffff pref]
[    1.140198] pci 0000:22:02.0: BAR 6: assigned [mem 0xfbb20000-0xfbb2ffff pref]
[    1.141200] pci_bus 0000:22: resource 4 [mem 0xfbb00000-0xfbffffff pref window]
[    1.142197] pci_bus 0000:22: resource 5 [mem 0xff100000-0xffafffff window]
[    1.143205] pci_bus 0000:22: resource 6 [io  0x0a00-0x0bff window]
[    1.144203] pci_bus 0000:23: resource 4 [mem 0xfac00000-0xfb0fffff pref window]
[    1.145200] pci_bus 0000:23: resource 5 [mem 0xfb100000-0xfbafffff window]
[    1.146200] pci_bus 0000:23: resource 6 [io  0x0d00-0x0eff window]
[    1.147209] NET: Registered protocol family 2
[    1.148177] IP idents hash table entries: 131072 (order: 8, 1048576 bytes)
[    1.150201] TCP established hash table entries: 65536 (order: 7, 524288 bytes)
[    1.151216] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes)
[    1.152213] TCP: Hash tables configured (established 65536 bind 65536)
[    1.153212] UDP hash table entries: 4096 (order: 5, 131072 bytes)
[    1.154212] UDP-Lite hash table entries: 4096 (order: 5, 131072 bytes)
[    1.155213] NET: Registered protocol family 1
[    1.155223] pci 0000:00:00.0: Limiting direct PCI/PCI transfers
[    1.156214] pci 0000:00:0f.0: Video device with shadowed ROM
[    1.157214] PCI: CLS 32 bytes, default 64
[    2.061720] Trying to unpack rootfs image as initramfs...
[    2.084733] Freeing initrd memory: 43992K
[    2.085108] redpill: loading out-of-tree module taints kernel.
[    2.085796] redpill: module verification failed: signature and/or required key missing - tainting kernel
[    2.087756] <redpill/redpill_main.c:46> ================================================================================================
[    2.089745] <redpill/redpill_main.c:47> RedPill v0.6-at-2023_05_02-08_24_44 loading...
[    2.091733] <redpill/call_protected.c:83> Got addr ffffffff811f08d0 for cmdline_proc_show
[    2.092749] <redpill/cmdline_delegate.c:350> Cmdline count: 402
[    2.093757] <redpill/cmdline_delegate.c:417> Cmdline: BOOT_IMAGE=/zImage-dsm withefi earlyprintk syno_hw_version=DS3622xs+ console=ttyS0,115200n8 netif_num=4 pid=0x0001 earlycon=uart8250,io,0x3f8,115200n8 synoboot_satadom=1 syno_port_thaw=1 mac1=001132EA412D sn=20C0SQRQLPH3J vid=0x46f4 elevator=elevator loglevel=15 HddHotplug=0 DiskIdxMap=0200 syno_hdd_detect=0 vender_format_version=2 syno_hdd_powerup_seq=0 log_buf_len=32M root=/dev/md0 SataPortMap=22
[    2.093757] 
[    2.101757] <redpill/cmdline_delegate.c:429> Param #0: |BOOT_IMAGE=/zImage-dsm|
[    2.102769] <redpill/cmdline_delegate.c:324> Option "BOOT_IMAGE=/zImage-dsm" not recognized - ignoring
[    2.103758] <redpill/cmdline_delegate.c:429> Param #1: |withefi|
[    2.104765] <redpill/cmdline_delegate.c:324> Option "withefi" not recognized - ignoring
[    2.105764] <redpill/cmdline_delegate.c:429> Param #2: |earlyprintk|
[    2.106756] <redpill/cmdline_delegate.c:324> Option "earlyprintk" not recognized - ignoring
[    2.107757] <redpill/cmdline_delegate.c:429> Param #3: |syno_hw_version=DS3622xs+|
[    2.108759] <redpill/cmdline_delegate.c:26> HW version set to: DS3622xs+
[    2.109773] <redpill/cmdline_delegate.c:429> Param #4: |console=ttyS0,115200n8|
[    2.110758] <redpill/cmdline_delegate.c:324> Option "console=ttyS0,115200n8" not recognized - ignoring
[    2.111763] <redpill/cmdline_delegate.c:429> Param #5: |netif_num=4|
[    2.112761] <redpill/cmdline_delegate.c:239> Declared network ifaces # as 4
[    2.113775] <redpill/cmdline_delegate.c:429> Param #6: |pid=0x0001|
[    2.114762] <redpill/cmdline_delegate.c:142> PID override: 0x0001
[    2.115765] <redpill/cmdline_delegate.c:429> Param #7: |earlycon=uart8250,io,0x3f8,115200n8|
[    2.116782] <redpill/cmdline_delegate.c:324> Option "earlycon=uart8250,io,0x3f8,115200n8" not recognized - ignoring
[    2.118778] <redpill/cmdline_delegate.c:429> Param #8: |synoboot_satadom=1|
[    2.119763] <redpill/cmdline_delegate.c:59> Boot media SATADOM (native) requested
[    2.120779] <redpill/cmdline_delegate.c:429> Param #9: |syno_port_thaw=1|
[    2.121764] <redpill/cmdline_delegate.c:211> Port thaw set to: 1
[    2.122766] <redpill/cmdline_delegate.c:429> Param #10: |mac1=001132EA412D|
[    2.123767] <redpill/cmdline_delegate.c:312> Set MAC #1: 001132EA412D
[    2.124770] <redpill/cmdline_delegate.c:429> Param #11: |sn=20C0SQRQLPH3J|
[    2.125781] <redpill/cmdline_delegate.c:45> S/N set to: 20C0SQRQLPH3J
[    2.126774] <redpill/cmdline_delegate.c:429> Param #12: |vid=0x46f4|
[    2.127783] <redpill/cmdline_delegate.c:108> VID override: 0x46f4
[    2.128770] <redpill/cmdline_delegate.c:429> Param #13: |elevator=elevator|
[    2.129774] <redpill/cmdline_delegate.c:324> Option "elevator=elevator" not recognized - ignoring
[    2.130785] <redpill/cmdline_delegate.c:429> Param #14: |loglevel=15|
[    2.131770] <redpill/cmdline_delegate.c:324> Option "loglevel=15" not recognized - ignoring
[    2.132775] <redpill/cmdline_delegate.c:429> Param #15: |HddHotplug=0|
[    2.133773] <redpill/cmdline_delegate.c:324> Option "HddHotplug=0" not recognized - ignoring
[    2.134772] <redpill/cmdline_delegate.c:429> Param #16: |DiskIdxMap=0200|
[    2.135776] <redpill/cmdline_delegate.c:324> Option "DiskIdxMap=0200" not recognized - ignoring
[    2.136770] <redpill/cmdline_delegate.c:429> Param #17: |syno_hdd_detect=0|
[    2.137790] <redpill/cmdline_delegate.c:324> Option "syno_hdd_detect=0" not recognized - ignoring
[    2.138786] <redpill/cmdline_delegate.c:429> Param #18: |vender_format_version=2|
[    2.139776] <redpill/cmdline_delegate.c:324> Option "vender_format_version=2" not recognized - ignoring
[    2.140776] <redpill/cmdline_delegate.c:429> Param #19: |syno_hdd_powerup_seq=0|
[    2.141781] <redpill/cmdline_delegate.c:324> Option "syno_hdd_powerup_seq=0" not recognized - ignoring
[    2.142786] <redpill/cmdline_delegate.c:429> Param #20: |log_buf_len=32M|
[    2.143780] <redpill/cmdline_delegate.c:324> Option "log_buf_len=32M" not recognized - ignoring
[    2.144781] <redpill/cmdline_delegate.c:429> Param #21: |root=/dev/md0|
[    2.145776] <redpill/cmdline_delegate.c:324> Option "root=/dev/md0" not recognized - ignoring
[    2.146779] <redpill/cmdline_delegate.c:429> Param #22: |SataPortMap=22|
[    2.147781] <redpill/cmdline_delegate.c:324> Option "SataPortMap=22" not recognized - ignoring
[    2.148790] <redpill/cmdline_delegate.c:388> Add cmdline blacklist "vid=" @ 0
[    2.149786] <redpill/cmdline_delegate.c:389> Add cmdline blacklist "pid=" @ 1
[    2.150783] <redpill/cmdline_delegate.c:390> Add cmdline blacklist "mfg" @ 2
[    2.151780] <redpill/cmdline_delegate.c:391> Add cmdline blacklist "dom_szmax=" @ 3
[    2.152793] <redpill/cmdline_delegate.c:392> Add cmdline blacklist "elevator=" @ 4
[    2.153784] <redpill/cmdline_delegate.c:393> Add cmdline blacklist "loglevel=" @ 5
[    2.154799] <redpill/cmdline_delegate.c:394> Add cmdline blacklist "log_buf_len=" @ 6
[    2.155784] <redpill/cmdline_delegate.c:395> Add cmdline blacklist "earlyprintk" @ 7
[    2.156786] <redpill/cmdline_delegate.c:396> Add cmdline blacklist "syno_port_thaw=" @ 8
[    2.157784] <redpill/cmdline_delegate.c:450> CmdLine processed successfully, tokens=23
[    2.158802] <redpill/runtime_config.c:187> Found platform definition for "DS3622xs+"
[    2.159790] <redpill/runtime_config.c:198> Validating runtime config...
[    2.160787] <redpill/runtime_config.c:64> Using native SATA-DoM boot - vid= and pid= parameter values will be ignored
[    2.162798] <redpill/runtime_config.c:76> Configured boot device type to fake-SATA DOM
[    2.163800] <redpill/runtime_config.c:142> Number of defined interfaces ("netif_num=4") is not equal to the number of MAC addresses found (1)
[    2.165807] <redpill/runtime_config.c:206> Config validation resulted in ERR
[    2.166805] <redpill/runtime_config.c:210> Config validation FAILED
[    2.167790] <redpill/runtime_config.c:220> Failed to populate runtime config!
[    2.168792] <redpill/redpill_main.c:75> RedPill v0.6-at-2023_05_02-08_24_44 cannot be loaded, initializer error=1
[    2.170807] Kernel panic - not syncing: Fatal exception
[    2.171790] CPU: 1 PID: 922 Comm: insmod Tainted: G           OE   4.4.302+ #64551
[    2.172802] Hardware name: VMware, Inc. VMware20,1/440BX Desktop Reference Platform, BIOS VMW201.00V.20829224.B64.2211211842 11/21/2022
[    2.174795]  0000000000000000 ffff880231dbbc50 ffffffff815656ad ffffffffa001d423
[    2.175786]  ffff880234b502c0 ffff880231dbbcc8 ffffffff815584fd 0000000000000008
[    2.176804]  ffff880231dbbcd8 ffff880231dbbc78 ffffffff81095f1a 0000000000000246
[    2.177807] Call Trace:
[    2.177815]  [<ffffffff815656ad>] dump_stack+0x57/0x6d
[    2.178802]  [<ffffffff815584fd>] panic+0xc6/0x21a
[    2.179788]  [<ffffffff81095f1a>] ? vprintk_default+0x1a/0x20
[    2.180796]  [<ffffffffa0027000>] ? 0xffffffffa0027000
[    2.181807]  [<ffffffffa000f788>] rp_crash+0x10/0x10 [redpill]
[    2.182789]  [<ffffffffa002715b>] init_+0x15b/0x18b [redpill]
[    2.183802]  [<ffffffff81000347>] do_one_initcall+0x87/0x130
[    2.184792]  [<ffffffff810bc3bb>] do_init_module+0x5b/0x200
[    2.185807]  [<ffffffff810be33a>] load_module+0x1d9a/0x2280
[    2.186799]  [<ffffffff810bad90>] ? symbol_put_addr+0x40/0x40
[    2.187808]  [<ffffffff81181f2c>] ? kernel_read+0x3c/0x50
[    2.188794]  [<ffffffff810be9d3>] SYSC_finit_module+0x73/0x90
[    2.189800]  [<ffffffff810bea09>] SyS_finit_module+0x9/0x10
[    2.190795]  [<ffffffff8157c08a>] entry_SYSCALL_64_fastpath+0x1e/0x93
[    2.191846] ---[ end Kernel panic - not syncing: Fatal exception
Connection closing...Socket close.
`

**Comment by pocopico** [comment]
Problem seems to be the disks addon. I need to revisit that.

**Comment by pocopico** [comment]
The disks addon issue has been solved, you can try to rebuild

**Comment by yyxida** [comment]
![image](https://github.com/pocopico/tinycore-redpill/assets/22792135/efdab5e8-afb8-497a-9f3e-382ab49b832f)
Can work normally, thank you very much.

**Comment by pocopico** [comment]
Super, OK to close then !
