### ISSUE TITLE
The Loader doesn't create boot partitions

### ISSUE THREAD

**Issue by teslaweiler** [pocopico/tinycore-redpill#304]
**Describe the bug**
The Loader doesn't create boot partitions

.

**Screenshots**
<img width="475" alt="Screenshot 2023-05-21 181937" src="https://github.com/pocopico/tinycore-redpill/assets/68001202/03802fe3-f4af-4c86-8c61-0eaec59e1fb5">
<img width="484" alt="Screenshot 2023-05-21 182011" src="https://github.com/pocopico/tinycore-redpill/assets/68001202/7df8b608-84a0-4dab-8305-895b0100a7d6">
<img width="475" alt="Screenshot 2023-05-21 182055" src="https://github.com/pocopico/tinycore-redpill/assets/68001202/698ff798-6d78-429d-bd87-7c9401506115">

**Desktop (please complete the following information):**
-CLI
 - putty
 - windows 11

**Additional context**

**Comment by pocopico** [comment]
fixed on latest version, please update
