### ISSUE TITLE
DS3622xs+ on baremetal not responding to IP after DSM install

### ISSUE THREAD

**Issue by GunterO** [pocopico/tinycore-redpill#306]
**Describe the bug**
Using the latest TCRP image 0.9.4.5 from 2023/05/21 18:43
The TCRP build is going well (html), and the installation of DSM 7.2-64551 is going well too (not stuck at 99% anymore).
But once it reboots after DSM is installed, there is no response to the IP anymore. Not able to ping either. The IP is fixed to 192.168.1.19 via MAC binding in my router. TCRP Friend is showing the IP correctly (see screenshot), but I can't connect to it, nor ping.
When using DS920+ as target, it works. 
Tried without the "real mac" option, but the machine is not getting a new IP, so can't connect either.

**To Reproduce**
Build via HTML with "real mac", version: 7.2.0-64551 (see attached logfile). Using .pat file downloaded from Synology website to install DSM (DSM_DS3622xs+_64551.pat). Boout TCRP Friend 0.0.5, see screenshot.

**Expected behavior**
Being able to connect to the IP that TCRP is showing.

**Screenshots**
![photo_2023-05-22_11-32-14](https://github.com/pocopico/tinycore-redpill/assets/7931134/95ba59cb-cf33-40ad-a74e-c7ee7266a145)

**Build log**
[20230522_tcrp_ds3622xs+.txt](https://github.com/pocopico/tinycore-redpill/files/11529500/20230522_tcrp_ds3622xs%2B.txt)

**Desktop (please complete the following information):**
- HTML 
- Chrome 113.0.5672.93

**Comment by pocopico** [comment]
I see you are using the real mac address, did you try to see if you have lights on LAN card after boot ?  Also did you check your router or DHCP server for an IP assignment to this MAC ADDRESS ?

**Comment by GunterO** [comment]
I've tried that, but neither the SATA nor USB option are working.
![photo_2023-05-22_17-05-06](https://github.com/pocopico/tinycore-redpill/assets/7931134/633ca8bf-2e17-47e9-ae7b-42aaa9e48ae3)

**Comment by pocopico** [comment]
[   52.410317] 41 d6 00 a0 ff ff ff [   52.413373] NMI watchdog: BUG: soft lockup - CPU#5 stuck for 41s! [scsi_id:5237]
ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ[   52.413373] Modules linked in: broadwellnk_synobios(PO)ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ usbhid uasÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ hid e1000e(OE) rtc_cmos(OE-) button(OE) usb_storage xhci_pci xhci_hcd ehci_pci ehci_hcd usbcore usb_common mv14xx(O) redpill(OE)
[   52.413379] CPU: 5 PID: 5237 Comm: scsi_id Tainted: P           OE   4.4.302+ #64551


The NMI watchdog claims on of the modules, my bets though go on RTC_CMOS as it appears right after that :

   52.159369] 30 62 22 a0 ff ff ff ff  [04] 0x020 	ffffffffa0226230	rtc_bandon_get_time+0x0/0x1d0 [broadwellnk_synobios]
[   52.170391] 90 64 22 a0 ff ff ff ff  [05] 0x028 	ffffffffa0226490	rtc_bandon_set_time+0x0/0x340 [broadwellnk_synobios]
[   52.181452] 30 24 00 a0 ff ff ff ff  [06] 0x030 	ffffffffa0002430	bios_get_fan_state+0x0/0x10 [redpill]
[   52.191168] 57 d5 00 a0 ff ff ff ff  [07] 0x038 	ffffffffa000d557	bios_VTK_SET_FAN_STATE_null_zero_int+0x0/0x27 [redpill]
[   52.202495] d0 70 22 a0 ff ff ff ff  [08] 0x040 	ffffffffa02270d0	GetSysTemperature+0x0/0x20 [broadwellnk_synobios]
[   52.213232] 20 25 00 a0 ff ff ff ff  [09] 0x048 	ffffffffa0002520	bios_get_cpu_temp+0x0/0x40 [redpill]
[   52.222863] f0 78 22 a0 ff ff ff ff  [10] 0x050 	ffffffffa02278f0	SYNODiskLedCtrlBy1475SGPIO+0x0/0xd0 [broadwellnk_synobios]
[   52.234432] a5 d5 00 a0 ff ff ff ff  [11] 0x058 	ffffffffa000d5a5	bios_VTK_SET_PWR_LED_null_zero_int+0x0/0x27 [redpill]
[   52.245553] 00 00 00 00 00 00 00 00  [12] 0x060 	          (null)	          (null)
[   52.253403] 00 00 00 00 00 00 00 00  [13] 0x068 	          (null)	          (null)
[   52.261229] 00 00 00 00 00 00 00 00  [14] 0x070 	          (null)	          (null)
[   52.269116] 04 d7 00 a0 ff ff ff ff  [15] 0x078 	ffffffffa000d704	shim_set_gpio_pin_usable+0x0/0x98 [redpill]
[   52.279386] e0 28 00 a0 ff ff ff ff  [16] 0x080 	ffffffffa00028e0	shim_get_gpio_pin_usable+0x0/0x10 [redpill]
[   52.289638] cc d5 00 a0 ff ff ff ff  [17] 0x088 	ffffffffa000d5cc	bios_VTK_SET_GPIO_PIN_BLINK_null_zero_int+0x0/0x27 [redpill]
[   52.301391] 00 64 22 a0 ff ff ff ff  [18] 0x090 	ffffffffa0226400	rtc_bandon_set_auto_poweron+0x0/0x90 [broadwellnk_synobios]
[   52.313094] 90 5f 22 a0 ff ff ff ff  [19] 0x098 	ffffffffa0225f90	rtc_get_auto_poweron+0x0/0x50 [broadwellnk_synobios]

**Comment by damienmillet** [comment]
same issue about uefi, try with legacy, work for me with usb boot.
Boot can be until 200sec.

**Comment by GunterO** [comment]
Thanks, but it is running perfectly with arpl-i18n, and going to stick with that for now.
