### ISSUE TITLE
DS3622xs+ with v0.9.4.6  failed for install DSM 7.2-64561 

### ISSUE THREAD

**Issue by stargateSGU** [pocopico/tinycore-redpill#307]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- HTML or CLI

**Additional context**

**Comment by stargateSGU** [comment]
Hi,

i have just upgrade my xpenology DSM 7.1.1-42962 to DSM 7.2-64561 with tinycore-redpill v0.9.4.6 and when install sudo ./rploader.sh build ds3622xsp-7.2.0-64561 auto an error not find the file zImage-001-3622xs+-64561-ramdisk-and-header

Thanks for your good job !

**Comment by damienmillet** [comment]
can use the template and add a screenshot pls

**Comment by stargateSGU** [comment]
Hi,

Thanks so much.

Have a nice day !
