### ISSUE TITLE
DS3622xs+ installation failed with DSM DS3622xs+_64561.pat

### ISSUE THREAD

**Issue by stargateSGU** [pocopico/tinycore-redpill#312]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- HTML or CLI

**Additional context**

**Comment by stargateSGU** [comment]
Hi,
I have an issue checksum error and finally installation failed.
install goes to homepage, DSM DS3622xs+_64561.pat install 100% successful and loops back to homepage again.
Don't work correctly

**Comment by pocopico** [comment]
Fixed
