### ISSUE TITLE
Failed to delete word files (issue)

### ISSUE THREAD

**Issue by teslaweiler** [pocopico/tinycore-redpill#315]
Error with building a loader

Failed to delete word files

<img width="490" alt="Screenshot 2023-05-24 224010" src="https://github.com/pocopico/tinycore-redpill/assets/68001202/7c14e835-e3ed-4403-84b8-3d9f7f871329">

**Comment by pocopico** [comment]
Can you try to use the HTML version of the builder ? 

just open your browser and point to your TCRP IP e.g http://192.168.1.111/

**Comment by pocopico** [comment]
No reply, closing
