### ISSUE TITLE
DS3622xs+ installation usb key failed with tinycore-redpill.v0.9.4.6.img

### ISSUE THREAD

**Issue by stargateSGU** [pocopico/tinycore-redpill#316]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- HTML or CLI

**Additional context**

**Comment by stargateSGU** [comment]
Hi,
During creating usb key with tinycore-redpill.v0.9.4.6.img i have an issue error :

![Sans titre](https://github.com/pocopico/tinycore-redpill/assets/87321820/95199aab-079a-467b-8015-71d1abb3891d)

**Comment by pocopico** [comment]
Sorry i needed to recreate the patch file is should now be ok

**Comment by stargateSGU** [comment]
Thanks so much :)
Have a nice day
