### ISSUE TITLE
System (VM) shuts down when trying to access webpage

### ISSUE THREAD

**Issue by ner00** [pocopico/tinycore-redpill#317]
**Describe the bug**
After installing DSM, the system (VM) shuts down as soon as I try to access the web interface. 
Quick summary:

**Host:**
- CPU: Intel i7 3370K
- Hypervisor: VMware Workstation 16.x

**Guest:**
- 8 GB RAM;
- 1 CPU, 4 cores;
- 1 SATA HDD with TCRP image (tinycore-redpill.v0.9.4.6.vmdk);
- 1 SATA HDD with 25GB (for DSM);
- 1 Ethernet adapter, bridge mode (tried e1000, e1000e, vmxnet3);

I tried 2 models (DS920+ and DS3622xs+), using DSM v7.1.1 build 42962; tried the usual manual route from SSH and also using the HTML builder.

In both cases I can start the installation fine, but it is suspiciously quick in my opinion; goes from 0% to 8%, then after 5 seconds jumps to 40%, 55%, 56%, 57%, 58%, 59%, 60% and restarts leaving the browser with a 10min. countdown ("installation" took less than 1min.). After restarting, whenever I try to load DSM web page I immediately get a 502 error - white page with Synology logo and the message "**Sorry, the page you are looking for is not found**." and then the VM just shuts down after 3 seconds.

Note: After "installing", on first boot friend reports "Ramdisk upgrade has been detected zImage upgrade has been detected".

**To Reproduce**
Use VMware and with TCRP VMDK image, build loader for DS920+ or DS3622xs+ (v7.1.1 build 42962). After booting, upload appropriate PAT in DSM installation page. Wait for system to reboot after extremely quick installation, try to access DSM again or let countdown page do it since it tries to reload automatically. VM will shutdown shortly after starting up.

**Expected behavior**
To not power off the system

**Screenshots**
short video: https://github.com/pocopico/tinycore-redpill/assets/2269603/aa978808-1152-4763-9844-0ddeae209708

**Desktop (please complete the following information):**
- Both HTML and CLI
 - Firefox and Brave
 - Version 113.0.2 and Version 1.51.118

**Comment by pocopico** [comment]
Please add a serial port to your VM with the following settings 
![image](https://github.com/pocopico/tinycore-redpill/assets/67732101/944aa4a5-c9ff-44c2-8751-1459a0b1aaf5)

Then use putty to access the serial port and see whats going on  

![image](https://github.com/pocopico/tinycore-redpill/assets/67732101/b5478940-33a5-44ec-be96-1ddb19f49965)

**Comment by ner00** [comment]
Thanks for these instructions, they will come in handy.

I was half-expecting to have to paste massive logs in here but for whatever strange reason today I did not have the issue described, not once, and I already did more than 10 individual tests from scratch, all worked without a hitch. So, I'm going to go ahead and close this issue.

Thank you for the prompt reply.
