### ISSUE TITLE
DSM 7 installation on NUC DN2820FYK

### ISSUE THREAD

**Issue by superdumnezeu** [pocopico/tinycore-redpill#32]
Hi, 

I am trying to install DSM 7. I was able to build the bootloader for DS918+. 

Unfortunately, after connecting to the Synology page, I can't get to the DSM installation page. I get the following error: We've detected errors on the hard drives (2), and the SATA ports have also been disabled. I successfully install it.

The installation is done on a NUC DN2820FYK which has a N2830 CPU (Bay Trail). When I run the satamap now command, the following is displayed: 

HBA: 00:13.0   Disks : 2
SataPortMap=2
DiskIdxMap=00

Do I need to build the bootloader for a Bay Trail specifically?

Thanks

**Comment by pocopico** [comment]
Hi, This is a typical indication of wrong SataPortMap and DiskIdxMap. Change to SataPortMap=58 and DiskIdxMap=0A00 and see how it goes.

**Comment by mizrachiran** [comment]
getting the same issue, tried with multiple configuration options (including SataPortMap=58 and DiskIdxMap=0A00, as advised above). 

Would appreciate your assistance.

![image](https://user-images.githubusercontent.com/617155/156779387-6f339394-fa7c-4343-9577-dfa2d3e89b34.png)

**Comment by pocopico** [comment]
Please consult forums
