### ISSUE TITLE
Can't install DSM 7.1.1

### ISSUE THREAD

**Issue by ikukhtikov** [pocopico/tinycore-redpill#326]
I am getting an error. How to decide?

tc@box:~$ ./rploader.sh build ds918p-7.1.1-42962
Rploader Version : 0.9.4.7
Loader source : https://github.com/pocopico/redpill-load.git Loader Branch : develop
Redpill module source : https://github.com/pocopico/redpill-lkm.git : Redpill module branch : master
Extensions :   all-modules
  eudev
  disks
  misc
  boot-wait
Extensions URL : "https://github.com/pocopico/tcrp-addons/raw/main/all-modules/rpext-index.json",
"https://github.com/pocopico/tcrp-addons/raw/main/eudev/rpext-index.json",
"https://github.com/pocopico/tcrp-addons/raw/main/disks/rpext-index.json",
"https://github.com/pocopico/tcrp-addons/raw/main/misc/rpext-index.json",
"https://github.com/pocopico/tcrp-addons/raw/main/boot-wait/rpext-index.json"
TOOLKIT_URL : https://sourceforge.net/projects/dsgpl/files/toolkit/DSM7.0/ds.bromolow-7.0.dev.txz/download
TOOLKIT_SHA : a5fbc3019ae8787988c2e64191549bfc665a5a9a4cdddb5ee44c10a48ff96cdd
SYNOKERNEL_URL : https://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/25426branch/bromolow-source/linux-3.10.x.txz/download
SYNOKERNEL_SHA : 18aecead760526d652a731121d5b8eae5d6e45087efede0da057413af0b489ed
COMPILE_METHOD : toolkit_dev
TARGET_PLATFORM       : ds918p
TARGET_VERSION    : 7.1.1
TARGET_REVISION : 42962
REDPILL_LKM_MAKE_TARGET : dev-v7
KERNEL_MAJOR : 4
MODULE_ALIAS_FILE :  modules.alias.4.json
SYNOMODEL : ds918p_42962
MODEL : DS918+
Local Cache Folder : /mnt/sdc3/auxfiles
DATE Internet : 01062023 Local : 01062023
Checking Internet Access -> OK
Checking if a newer version exists on the main repo -> Version is current
Redpill sources already downloaded, pulling latest
Already up to date.
Loader sources already downloaded, pulling latest
Already up to date.
No extra build option or static specified, using default <static>
Using static compiled redpill extension
Removing any old redpill.ko modules
Looking for redpill for : ds918p_42962
Module does not contain platorm information for ds918p_42962

**Comment by pocopico** [comment]
I need to look at this, can you please in the meanwhile use the web builder instead ? 

Use an browser to access the TCRP IP eg http://yourtcrpip

**Comment by mrbulldog32** [comment]
> I need to look at this, can you please in the meanwhile use the web builder instead ?
> 
> Use an browser to access the TCRP IP eg http://yourtcrpip

In web compiled good:)i dont know that web version present)

**Comment by pocopico** [comment]
Super ! CLI has been fixed as well.
