### ISSUE TITLE
DVA3221 7.2-64561 -- Hard Disk error

### ISSUE THREAD

**Issue by lzzsalvo** [pocopico/tinycore-redpill#330]
Hi @pocopico, I tried to install DVA3221 using the latest release and also the 2 previous ones. The creation of the boot loader is successful but it doesn't allow me to install the operating system because the error appears on the disks. I'm running a test on a virtual machine with 2 x 1TB sata HDDs. I'm using the same HW settings as other models (DS3622xs+, DS923+, RS4021xs+) and I have no problems on these. I am attaching the logs and some screenshots. For all tests I used the HTML version.
![1](https://github.com/pocopico/tinycore-redpill/assets/95186977/3a9bd37e-2832-4d02-a44f-48e9bd8a7fe2)
![2](https://github.com/pocopico/tinycore-redpill/assets/95186977/ca6ce60c-6344-42e7-8879-00dba3078718)
[buildlog (1).txt](https://github.com/pocopico/tinycore-redpill/files/11645300/buildlog.1.txt)

**Comment by pocopico** [comment]
Can you please recreate the loader as i applied some critical fixes couple of minutes ago

**Comment by lzzsalvo** [comment]
Hi, I just tried with the latest version found on the site. Same problem reoccurs. The system detects disk 7 and 8 but in reality they are only 2 and I imagine, as happens with DS3622xs+, that it shows them as 2 and 3. Possible disk mapping problem?

**Comment by bdrwu** [comment]
sorry how to use the webUI ?

**Comment by pocopico** [comment]
Yes DiskIdxMap, you can play around with that but if you don’t mind it’s just a cosmetic issue

**Comment by lzzsalvo** [comment]
I'm sorry but it's not just cosmetic! unfortunately it doesn't let me install and configure the system! can't find the hdds!

> Il giorno 4 giu 2023, alle ore 13:49, pocopico ***@***.***> ha scritto:
> 
> Yes DiskIdxMap, you can play around with that but if you don’t mind it’s just a cosmetic issue

**Comment by pocopico** [comment]
DVA is using DT. Strange thought I need to test more

**Comment by pocopico** [comment]
There was an issue with disks falling outside the maxdisks value, can you try again ? I’ve changed it to default at maxdisks=16 if disks are less than 16

**Comment by lzzsalvo** [comment]
HI! have you had the opportunity to test?Il giorno 4 giu 2023, alle ore 15:51, pocopico ***@***.***> ha scritto:﻿
DVA is using DT. Strange thought I need to test more

**Comment by pocopico** [comment]
Yes, just tested a clean build & install of DVA3221 7.2.0 works as expected.
