### ISSUE TITLE
DVA1622 7.2 can't repair San Manager

### ISSUE THREAD

**Issue by calimansi** [pocopico/tinycore-redpill#331]
**Describe the bug**
I created a USB boot disk for DVA1622 with the 7.2 firmware.  From a blank hard drive, I install the OS.  When the OS comes up, the San Manager is broken with the option to repair.  I attempt to repair and it is still broken.  Going into SSH, I can't find any real issues except that it can't startup.

I was running the latest version of 7.1.1 great and this San Manager issue came up when I upgraded to 7.2.  I thought it was my end and tried re-creating my USB and formatting my hard drive in windows.  I'm thinking I have to go back down to 7.1.1... we'll see though.

**Comment by calimansi** [comment]
I should note that everything else seems to work... even the new container manager.  I just can't do any VM's because San Manager is required for that.

**Comment by pocopico** [comment]
Can you try the following ? At TCRP friend stop by pressing ctrl-c and execute 
prm 
And then boot.sh

**Comment by calimansi** [comment]
I downgraded to 7.1.1.  San Manager works.  Feels like 7.2 is still beta for DVA1622...  I think this is a synology issue.

**Comment by calimansi** [comment]
7.1.1 also feels snappier than 7.2 for now.  I'm sure synology needs to do some bug fixes.

**Comment by pocopico** [comment]
After running the following on a test system, i was able to repair the SAN MANAGER : 


modprobe iscsi_tcp
modprobe iscsi_target_mod
modprobe libiscsi
modprobe libiscsi_tcp
modprobe iscsi_target_mod
modprobe target_core_mod

**Comment by calimansi** [comment]
Ok... I'll try to upgrade to 7.2

**Comment by calimansi** [comment]
Holy crap it worked!!!  Genius you are.

**Comment by calimansi** [comment]
Survived a reboot too.

**Comment by pocopico** [comment]
Super then i can close the issue 👍
