### ISSUE TITLE
DSM7.1.1 installation system loopfor rs4021

### ISSUE THREAD

**Issue by yyxida** [pocopico/tinycore-redpill#335]
Using the following command to install the 7.1.1 system of rs4021 will enter a recovery loop, but the same command ds3622 does not have this issue.

./rploader.sh update
./rploader.sh fullupgrade
[Set satamap and sn/mac]
./rploader.sh listmods 【xxxx】-7.1.1-42962
./rploader.sh build 【xxxx】-7.1.1-42962

**Comment by pocopico** [comment]
Please download latest image and use the html builder instead

**Comment by yyxida** [comment]
> Please download latest image and use the html builder instead

I need to set up a proxy to access resources on GitHub and cannot use HTML for settings. Sorry

**Comment by yyxida** [comment]
> Once you boot at recovery, can you please provide the following by accessing the IP:7681 with user root and empty password
> 
> cat /var/log/linuxrc.syno.log cat /var/log/_junior_ cat /exts/extlog.log
[log.txt](https://github.com/pocopico/tinycore-redpill/files/11752149/log.txt)
Thank you

**Comment by pocopico** [comment]
You are using TCRP Friend right ?

**Comment by yyxida** [comment]
> You are using TCRP Friend right ? You have a kernel mismatch and that leads to root not matching junior. Select Tinycore Friend and let TCRP Friend boot.

Sorry, I started directly using 'RedPill RS4021xs+7.1.1-42962 (SATA, Verbose)' because I am aware that I am using Sata virtual hard disk to boot. I will try using TCRP Friend boot tomorrow.

**Comment by yyxida** [comment]
> You are using TCRP Friend right ? You have a kernel mismatch and that leads to root not matching junior. Select Tinycore Friend and let TCRP Friend boot.

Wow, I didn't even recompile, I just changed the startup options to be friendly and able to enter the system. How did he do it? 
Because I understand the meaning of satamap, I originally preferred to use the “sata boot ”option。Is there any difference between the option of 'friendly' and the original Sata or USB?
