### ISSUE TITLE
N3160 with i210 loader build Failed for ds3622xs-64570,what can I do?

### ISSUE THREAD

**Issue by tonyk520** [pocopico/tinycore-redpill#341]
[#] Extension eudev for ds3622xsp_64570 platform is already up to date
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/tcrp-addons/main/misc/recipes/universal.json to /home/tc/redpill-load/custom/extensions/_ext_new_rcp.tmp_json
############################################################################################################################################ 100.0%
[#] Extension misc for ds3622xsp_64570 platform is already up to date
[-] The extension pocopico.igb was found. However, the extension index has no recipe for ds3622xsp_64570 platform. It may not be
[-] supported on that platform, or author didn't updated it for that platform yet. You can try running
[-] "ext-manager.sh update" to refresh indexes for all extensions manually. Below are the currently known information about
[-] the extension stored locally:
[#] ========================================== pocopico.igb ==========================================
[#] Extension name: igb
[#] Description: Adds Intel(R) Gigabit Ethernet Network Driver Support
[#] To get help visit: <todo>
[#] Extension preparer/packer: https://github.com/pocopico/rp-ext/tree/main/igb
[#] Software author: https://github.com/pocopico
[#] Update URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/igb/rpext-index.json
[#] Platforms supported: ds1621p_42218 ds1621p_42951 ds918p_41890 dva3221_42661 ds3617xs_42621 ds3617xs_42218 ds920p_42661 dva3221_42962 ds918p_42661 ds3622xsp_42962 ds3617xs_42951 dva1622_42218 dva1622_42621 ds920p_42962 ds1621p_42661 dva1622_42951 ds918p_25556 dva3221_42218 ds3615xs_42661 dva3221_42951 ds3622xsp_42661 ds2422p_42661 ds3622xsp_42218 ds2422p_42962 rs4021xsp_42621 dva1622_42962 ds2422p_42218 rs4021xsp_42962 dva3221_42621 ds3615xs_42962 ds3617xs_42962 ds3615xs_41222 ds920p_42951 rs4021xsp_42218 ds2422p_42951 ds918p_42621 ds3617xs_42661 ds3615xs_25556 ds920p_42218 rs4021xsp_42951 ds920p_42621 ds918p_42962 ds3615xs_42951 ds3622xsp_42951 dva1622_42661 ds918p_42218 ds2422p_42621 ds1621p_42621 ds3615xs_42621 ds3615xs_42218 ds1621p_42962 ds3622xsp_42621 rs4021xsp_42661 
[#] =======================================================================================

[-] Failed to update recipe for pocopico.igb extension for platform ds3622xsp_64570. The script will terminate as you do not
[-] have previously downloaded recipe which can be used if download fails. Try again later. If problem
[-] persists contact the extension packer for support (displayed below)
[#] ========================================== pocopico.igb ==========================================
[#] Extension name: igb
[#] Description: Adds Intel(R) Gigabit Ethernet Network Driver Support
[#] To get help visit: <todo>
[#] Extension preparer/packer: https://github.com/pocopico/rp-ext/tree/main/igb
[#] Software author: https://github.com/pocopico
[#] Update URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/igb/rpext-index.json
[#] Platforms supported: ds1621p_42218 ds1621p_42951 ds918p_41890 dva3221_42661 ds3617xs_42621 ds3617xs_42218 ds920p_42661 dva3221_42962 ds918p_42661 ds3622xsp_42962 ds3617xs_42951 dva1622_42218 dva1622_42621 ds920p_42962 ds1621p_42661 dva1622_42951 ds918p_25556 dva3221_42218 ds3615xs_42661 dva3221_42951 ds3622xsp_42661 ds2422p_42661 ds3622xsp_42218 ds2422p_42962 rs4021xsp_42621 dva1622_42962 ds2422p_42218 rs4021xsp_42962 dva3221_42621 ds3615xs_42962 ds3617xs_42962 ds3615xs_41222 ds920p_42951 rs4021xsp_42218 ds2422p_42951 ds918p_42621 ds3617xs_42661 ds3615xs_25556 ds920p_42218 rs4021xsp_42951 ds920p_42621 ds918p_42962 ds3615xs_42951 ds3622xsp_42951 dva1622_42661 ds918p_42218 ds2422p_42621 ds1621p_42621 ds3615xs_42621 ds3615xs_42218 ds1621p_42962 ds3622xsp_42621 rs4021xsp_42661 
[#] =======================================================================================

[!] Cannot continue due to previous errors (see above)

*** Process will exit ***
[!] Failed to update all extensions for ds3622xsp_64570 platform - see errors above

*** Process will exit ***
FAILED : Loader creation failed check the output for any errors
tc@box:~$

**Comment by yyxida** [comment]
https://github.com/pocopico/redpill-modules，7.2的系统不需要手动添加驱动，编译会自动包含（绝大部分的）驱动包

**Comment by tonyk520** [comment]
I Compile by default like follow:
./rploader.sh update
./rploader.sh fullupgrade
./rploader.sh serialgen DS3622xs+
./rploader.sh satamap
./rploader.sh identifyusb
./rploader.sh ext ds3622xsp-7.2.0-64570

unfortunately prompt 
The extension pocopico.igb was found. However, the extension index has no recipe for ds3622xsp_64570 platform. It may not be supported on that platform...
the  Platforms supported list lack ds3622xsp_64570

**Comment by yyxida** [comment]
> ./rploader.sh ext ds3622xsp-7.2.0-64570 auto

No need for this command， 7.2 does not require manual driver settings

**Comment by tonyk520** [comment]
> > ./rploader.sh ext ds3622xsp-7.2.0-64570 auto
> 
> No need for this command， 7.2 does not require manual driver settings
> 
> ./rploader.sh update ./rploader.sh fullupgrade ./rploader.sh serialgen DS3622xs+ ./rploader.sh satamap ./rploader.sh identifyusb ./rploader.sh build ds3622xsp-7.2.0-64570

Thanks a lot. But the update 64570-1 has just been released so no suitable pat to download now. I will try again later when TCRP update

**Comment by yyxida** [comment]
> Thanks a lot. But the update 64570-1 has just been released so no suitable pat to download now. I will try again later when TCRP update

It has been updated and can be compiled after the update operation
./rploader.sh update
./rploader.sh fullupgrade

**Comment by pocopico** [comment]
Please skip the listmodules part or use the HTML Builder by accessing TCRP through your browser http://yourtcrpip

**Comment by tonyk520** [comment]
Yes, I chose the last option, which is the Friend one to boot the dsm,but again an again,it prompted not installed,no mater use old 7.2.0 pat or 7.2.0-u1 pat file,online or offline...

**Comment by tonyk520** [comment]
and I also change the SATA port,still the same result

**Comment by pocopico** [comment]
Can you please login using the http://yourip:7681 (root and no pass) and check the following 

cat /var/log/junior*
cat /var/log/linux*

**Comment by tonyk520** [comment]
SynologyNAS login: root

Using terminal commands to modify system configs, execute external binary
files, add files, or install unauthorized third-party apps may lead to system
damages or unexpected behavior, or cause data loss. Make sure you are aware of
the consequences of each command and proceed at your own risk.

Warning: Data should only be stored in shared folders. Data stored elsewhere
may be deleted when the system is updated/restarted.



BusyBox v1.30.1 () built-in shell (ash)

SynologyNAS> cat /var/log/junior*
Exit on error [99] rp ext init exec failure...
2023-06-23T07:00:25+00:00 junior_expansion_pack.sh [7012][info]: [ENTER] main 
2023-06-23T07:00:25+00:00 junior_expansion_pack.sh [7012][info]: Starting JuniorExpansionPack [/tmp/JEP.jep] -> [/tmp/JEP.extract][/usr/syno/JEP.HEADER]
2023-06-23T07:00:25+00:00 junior_expansion_pack.sh [7012][info]: [ENTER] JuniorExpansionPack download /tmp/JEP.jep
2023-06-23T07:00:25+00:00 junior_expansion_pack.sh [7012][info]: [ENTER] JuniorExpansionPack url
2023-06-23T07:00:25+00:00 junior_expansion_pack.sh [7012][info]: [EXIT]  JuniorExpansionPack url
2023-06-23T07:00:25+00:00 junior_expansion_pack.sh [7012][info]: Trying to obtain from https://dataupdate7.synology.com/juniorexpansionpack/v1/getUpdate?platform=broadwellnk&buildnumber=64570 [1]
2023-06-23T07:00:25+00:00 junior_expansion_pack.sh [7012][err]: Failed to curl [https://dataupdate7.synology.com/juniorexpansionpack/v1/getUpdate?platform=broadwellnk&buildnumber=64570][7]
2023-06-23T07:00:55+00:00 junior_expansion_pack.sh [7012][info]: Trying to obtain from https://dataupdate7.synology.com/juniorexpansionpack/v1/getUpdate?platform=broadwellnk&buildnumber=64570 [11]
2023-06-23T07:00:55+00:00 junior_expansion_pack.sh [7012][err]: Failed to curl [https://dataupdate7.synology.com/juniorexpansionpack/v1/getUpdate?platform=broadwellnk&buildnumber=64570][7]
2023-06-23T07:01:25+00:00 junior_expansion_pack.sh [7012][info]: Trying to obtain from https://dataupdate7.synology.com/juniorexpansionpack/v1/getUpdate?platform=broadwellnk&buildnumber=64570 [21]
2023-06-23T07:01:25+00:00 junior_expansion_pack.sh [7012][err]: Failed to curl [https://dataupdate7.synology.com/juniorexpansionpack/v1/getUpdate?platform=broadwellnk&buildnumber=64570][7]
SynologyNAS> cat /var/log/linux*
START /linuxrc.syno.impl
Insert Marvell 1475 SATA controller driver
Insert basic USB modules...
:: Loading module usb-common ... [  OK  ]
:: Loading module usbcore ... [  OK  ]
:: Loading module ehci-hcd ... [  OK  ]
:: Loading module ehci-pci ... [  OK  ]
:: Loading module xhci-hcd ... [  OK  ]
:: Loading module xhci-pci ... [  OK  ]
:: Loading module usb-storage ... [  OK  ]
:: Loading kernel modules from extensions ...
:: Loading kernel modules from extensions ... [  OK  ]
:: Executing "on_boot" custom scripts ...
Running "install.sh" for all-modules->on_boot
/exts/exec.sh: .: line 35: can't open './install.sh': No such file or directory
Ran "install.sh" for all-modules->on_boot - exit=2
Running "boot-wait.sh" for boot-wait->on_boot
Still waiting for boot device (waited 1 of 10 seconds)
Still waiting for boot device (waited 2 of 10 seconds)
Ran "boot-wait.sh" for boot-wait->on_boot - exit=0
Running "install.sh" for disks->on_boot
System is booting
'dtc' -> '/usr/sbin/dtc'
'readlink' -> '/usr/sbin/readlink'
'sed' -> '/usr/sbin/sed'
Adjust disks related configs automatically - patches
get maxdisks=16
maxdisks=16
internalportcfg=
esataportcfg=0
usbportcfg=3145728
Ran "install.sh" for disks->on_boot - exit=0
Running "install.sh" for eudev->on_boot
/exts/exec.sh: .: line 35: can't open './install.sh': No such file or directory
Ran "install.sh" for eudev->on_boot - exit=2
Running "install_rd.sh" for misc->on_boot
Starting ttyd, listening on port: 7681
Ran "install_rd.sh" for misc->on_boot - exit=0
ERROR: Some of the scripts failed! See above for any with exit != 0
:: Executing "on_boot" custom scripts ... [  OK  ]
Exit on error [99] rp ext init exec failure...
Fri Jun 23 07:00:02 UTC 2023
none /sys/kernel/debug debugfs rw,relatime 0 0
SynologyNAS> cat /exts/extlog.log
cat: can't open '/exts/extlog.log': No such file or directory
SynologyNAS>
