### ISSUE TITLE
CONSOLE STUCK ON BOOTING KERNEL

### ISSUE THREAD

**Issue by kushalg-1212** [pocopico/tinycore-redpill#345]
**Describe the bug**
STUCK ON BOOTING KERNEL 

**To Reproduce**
REBOOT DSM

**Expected behavior**
Maybe some sort of console 

**Screenshots**
Screenshot Attached

![image](https://github.com/pocopico/tinycore-redpill/assets/111343538/edcee64b-a55a-4a39-b73b-6f5e97047305)

**Desktop (please complete the following information):**
HTML 
 - Browser GOOGLE CHROME/BRAVE/FIREFOX

**Additional context**
DSM is working FINE , but the console is stuck on booting kernel , is this expected ?

**Comment by pocopico** [comment]
Yea that’s expected. You can only see messages past that using the serial port com1

**Comment by kushalg-1212** [comment]
> Yea that’s expected. You can only see messages past that using the serial port com1

Thanks 
Closing this issue
