### ISSUE TITLE
3622xsp DSM 7.2.0-64570 build error

### ISSUE THREAD

**Issue by mitkovip** [pocopico/tinycore-redpill#352]
Trying to create image but getting error:
[-] The extension pocopico.igb was found. However, the extension index has no recipe for ds3622xsp_64570 platform. It may not be
[-] supported on that platform, or author didn't updated it for that platform yet. You can try running
[-] "ext-manager.sh update" to refresh indexes for all extensions manually. Below are the currently known information about
[-] the extension stored locally:
[#] ========================================== pocopico.igb ==========================================
[#] Extension name: igb
[#] Description: Adds Intel(R) Gigabit Ethernet Network Driver Support
[#] To get help visit: <todo>
[#] Extension preparer/packer: https://github.com/pocopico/rp-ext/tree/main/igb
[#] Software author: https://github.com/pocopico
[#] Update URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/igb/rpext-index.json
[#] Platforms supported: ds1621p_42218 ds1621p_42951 ds918p_41890 dva3221_42661 ds3617xs_42621 ds3617xs_42218 ds920p_42661 dva3221_42962 ds918p_42661 ds3622xsp_42962 ds3617xs_42951 dva1622_42218 dva1622_42621 ds920p_42962 ds1621p_42661 dva1622_42951 ds918p_25556 dva3221_42218 ds3615xs_42661 dva3221_42951 ds3622xsp_42661 ds2422p_42661 ds3622xsp_42218 ds2422p_42962 rs4021xsp_42621 dva1622_42962 ds2422p_42218 rs4021xsp_42962 dva3221_42621 ds3615xs_42962 ds3617xs_42962 ds3615xs_41222 ds920p_42951 rs4021xsp_42218 ds2422p_42951 ds918p_42621 ds3617xs_42661 ds3615xs_25556 ds920p_42218 rs4021xsp_42951 ds920p_42621 ds918p_42962 ds3615xs_42951 ds3622xsp_42951 dva1622_42661 ds918p_42218 ds2422p_42621 ds1621p_42621 ds3615xs_42621 ds3615xs_42218 ds1621p_42962 ds3622xsp_42621 rs4021xsp_42661
[#] =======================================================================================

[-] Failed to update recipe for pocopico.igb extension for platform ds3622xsp_64570. The script will terminate as you do not
[-] have previously downloaded recipe which can be used if download fails. Try again later. If problem
[-] persists contact the extension packer for support (displayed below)
[#] ========================================== pocopico.igb ==========================================
[#] Extension name: igb
[#] Description: Adds Intel(R) Gigabit Ethernet Network Driver Support
[#] To get help visit: <todo>
[#] Extension preparer/packer: https://github.com/pocopico/rp-ext/tree/main/igb
[#] Software author: https://github.com/pocopico
[#] Update URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/igb/rpext-index.json
[#] Platforms supported: ds1621p_42218 ds1621p_42951 ds918p_41890 dva3221_42661 ds3617xs_42621 ds3617xs_42218 ds920p_42661 dva3221_42962 ds918p_42661 ds3622xsp_42962 ds3617xs_42951 dva1622_42218 dva1622_42621 ds920p_42962 ds1621p_42661 dva1622_42951 ds918p_25556 dva3221_42218 ds3615xs_42661 dva3221_42951 ds3622xsp_42661 ds2422p_42661 ds3622xsp_42218 ds2422p_42962 rs4021xsp_42621 dva1622_42962 ds2422p_42218 rs4021xsp_42962 dva3221_42621 ds3615xs_42962 ds3617xs_42962 ds3615xs_41222 ds920p_42951 rs4021xsp_42218 ds2422p_42951 ds918p_42621 ds3617xs_42661 ds3615xs_25556 ds920p_42218 rs4021xsp_42951 ds920p_42621 ds918p_42962 ds3615xs_42951 ds3622xsp_42951 dva1622_42661 ds918p_42218 ds2422p_42621 ds1621p_42621 ds3615xs_42621 ds3615xs_42218 ds1621p_42962 ds3622xsp_42621 rs4021xsp_42661
[#] =======================================================================================

I can create it via http but user_config is overwriten and i am unable to modify paramteres (number of LAN)

**Comment by pocopico** [comment]
You can modify it at the end
