### ISSUE TITLE
7.1 upgrade to Ds920p-7.2.0-64570

### ISSUE THREAD

**Issue by vysecurity** [pocopico/tinycore-redpill#371]
**Describe the bug**
Have a problem to upgrade from 7.1 to 7.2 Update 3. I upgraded in the Synology GUI then turned out the machine won't boot anymore. So I went to TCRP and ran the following command:

```
   ./rploader.sh serialgen DS920+
   ./rploader.sh serialgen DS920+ realmac
   ./rploader.sh identifyusb
   ./rploader.sh satamap
   ./rploader.sh ext ds920p-7.2.0-64570 add https://raw.githubusercontent.com/vysecurity/synology-igc/main/igc/rpext-index.json
   ./rploader.sh ext ds920p-7.2.0-64570 add https://raw.githubusercontent.com/pocopico/tcrp-addons/main/all-modules/rpext-index.json
   ./rploader.sh backup
    ./rploader.sh build ds920p-7.2.0-64570
   exitcheck.sh poweroff
```

I went into the TCRP Friend, found that there's an IP configuration flaw, so I fixed it by hardcoding the right interface. Then afterwards, it still won't boot after the kext is loaded.

**Expected behavior**
Synology DSM loads and runs 7.2.0

**Additional context**
DX4600 running 7.1, upgraded to 7.2.

**Comment by vysecurity** [comment]
Is the loader broken? I think it's basically not loading DSM correctly.

**Comment by pocopico** [comment]
Do not add manually the igc module it's already included in the all-modules addon

**Comment by vysecurity** [comment]
thanks sorted!
