### ISSUE TITLE
On Proxmox VE, the display is blurred after entering the tinycore system

### ISSUE THREAD

**Issue by yyxida** [pocopico/tinycore-redpill#378]
**Describe the bug**
v0.10.0，uefi boot on Proxmox VE, the display is blurred after entering the tinycore system

**To Reproduce**
Set up boot and start normally

**Expected behavior**
nope

**Screenshots**
![image](https://github.com/pocopico/tinycore-redpill/assets/22792135/9c4bf1d3-de5f-4f8f-9fd6-68a33da79006)

**Desktop (please complete the following information):**
![image](https://github.com/pocopico/tinycore-redpill/assets/22792135/c57c5842-bec0-4ece-a755-e84a7efb0cfc)
The display settings of the virtual machine are all default
**Additional context**
Although I can find the IP address on the router, since I have discovered this issue, I think it is necessary to raise it

Thank you for your work. The new version is great！

**Comment by lwx16917** [comment]
It seems to be a problem with display driver. Can be mitigated by using other display adapters like `VMware compatible(vmware)` or `SPICE(qxl)`.

On some distro(i.e. I tried Clonezilla) you can delete the `nomodeset` on grub option(press E when you select boot option) but the TC image at here doesn't use that one. Everything on the web interface still works and can be run from ssh, just corrupted display for noVNC console.

https://forum.proxmox.com/threads/novnc-vm-console-graphics-corruption-default-vga.67984/
https://xcp-ng.org/forum/topic/3408/scrambled-display-booting-clonezilla-and-linux-isos-under-win10-template

**Comment by yyxida** [comment]
> It seems to be a problem with display driver. Can be mitigated by using other display adapters like `VMware compatible(vmware)` or `SPICE(qxl)`.
> 
> On some distro(i.e. I tried Clonezilla) you can delete the `nomodeset` on grub option(press E when you select boot option) but the TC image at here doesn't use that one. Everything on the web interface still works and can be run from ssh, just corrupted display for noVNC console.
> 
> https://forum.proxmox.com/threads/novnc-vm-console-graphics-corruption-default-vga.67984/ https://xcp-ng.org/forum/topic/3408/scrambled-display-booting-clonezilla-and-linux-isos-under-win10-template

Yes, later I also had the same problem when installing an older version of Ubuntu, so it appeared to be a tinycore issue. I resolved it after replacing the VMware compatible display.
