### ISSUE TITLE
How to install 7.2.1-69057?

### ISSUE THREAD

**Issue by delifruit** [pocopico/tinycore-redpill#379]
I tried to insatll 7.2.1-69057 with new version 0.10.0.0
but when excuting rploader.sh build command, I can't see 7.2.1-69057.

I wonder how to install 7.2.1-69057 with this loader?

Thank you.

**Comment by 007fred50** [comment]
hello,

type "./rploader.sh build" and you will see all build you can install

**Comment by fvascotto** [comment]
The platform 7.2.1-69057 is missing in the custom_config.json file. It has to be fixed, meanwhile you can edit your custom_config.json file, duplicating the version 7.2.0-64570 of the platform you need and replacing the "7.2.0-64570" string with "7.2.1-69057".
Here is the code fragment you need to add, e.g., for the DS918+ platform.

    {
      "id": "ds918p-7.2.1-69057",
      "platform_version": "ds918p-7.2.1-69057",
      "user_config_json": "r1000_user_config.json",
	   "docker_base_image": "debian:8-slim",
      "compile_with": "toolkit_dev",
      "redpill_lkm_make_target": "dev-v7",
      "downloads": {
        "kernel": {
          "url": "https://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/25426branch/bromolow-source/linux-3.10.x.txz/download",
          "sha256": "18aecead760526d652a731121d5b8eae5d6e45087efede0da057413af0b489ed"
        },
        "toolkit_dev": {
          "url": "https://sourceforge.net/projects/dsgpl/files/toolkit/DSM7.0/ds.bromolow-7.0.dev.txz/download",
          "sha256": "a5fbc3019ae8787988c2e64191549bfc665a5a9a4cdddb5ee44c10a48ff96cdd"
        }
      },
      "redpill_lkm": {
        "source_url": "https://github.com/pocopico/redpill-lkm.git",
        "branch": "master"
      },
      "redpill_load": {
        "source_url": "https://github.com/pocopico/redpill-load.git",
        "branch": "develop"
      },
      "add_extensions": [
        {
          "all-modules": "https://github.com/pocopico/tcrp-addons/raw/main/all-modules/rpext-index.json",
          "eudev": "https://github.com/pocopico/tcrp-addons/raw/main/eudev/rpext-index.json",
          "disks": "https://github.com/pocopico/tcrp-addons/raw/main/disks/rpext-index.json",
          "misc": "https://github.com/pocopico/tcrp-addons/raw/main/misc/rpext-index.json"
        }
      ]
    },

**Comment by pocopico** [comment]
You can use the HTML builder for 7.2.1. Open a browser and enter http://yourip/index.sh

**Comment by delifruit** [comment]
Thank you fvascotto and pocopico.
I have upgraded 7.2.1-69057 via HTML builder and 
using rploader.sh by modifying custom_config.json separately.

**Comment by tenuring210** [comment]
Hello, I am trying to install 7.2.1-69057 just like delifruit. I am not able to follow above instructions. Could somebody please help? I am trying to do this on ds3622xp+... @pocopico
