### ISSUE TITLE
mpt3sas & mpt2sas on DS918p not detecting sas drives on boot

### ISSUE THREAD

**Issue by SyraTi** [pocopico/tinycore-redpill#42]
I have a LSI SAS2008 IT running on ASROCK H81m-itx.
At First, I build the loader with the automatic 
```shell
./rploader.sh serialgen apollolake-7.0.1-42218
./rploader.sh usbidentify now
./rploader.sh satamap now
./rploader.sh build apollolake-7.0.1-42218
```
With this loader, the NAS did not get ip and I cannot reach synology webpage. and if I unload the HBA card and reboot, all works fine.

After searching the internet, I found this issue #14 but it was for DS3615xs.  
I tried it to DS918+ by ```sudo ./rploader.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/mpt2sas/rpext-index.json``` and find it works!

now I can normally reach the webpage but theres another problem that the synology cannot detect my sas drive attached to my HBA card.

I tried everything like ```add pocopico.mptsas``` , ```change SataPortMap to AAAA``` but nothing works.

**Comment by Dvalin21** [comment]
Have you tried using megaraid_sas instead of any of the mptsas?  I have close to the same card except mine using the megaraid_sas and I was only able to get ds3622xs to install on drives attached the card. Also I used the defaults 58 and 0A00, but have not had the chance to test anything else.
