### ISSUE TITLE
ERROR in build apollolake-7.0.1-42218

### ISSUE THREAD

**Issue by naoki66** [pocopico/tinycore-redpill#44]
Checking if a newer version exists on the repo ->    This process is very slow。

gzip: modules.alias.3.json.gz: No such file or directory

[!] Failed to download https://github.com/jumkey/redpill-load/raw/develop/redpill-boot-wait/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json

*** Process will exit ***

[-] Failed to download index file for thethorgroup.boot-wait extension from https://github.com/jumkey/redpill-load/raw/develop/redpill-boot-wait/rpext-index.json

Can I keep these downloaded files without entering into tinycore  every time  download again?

**Comment by pocopico** [comment]
Sure, you can perform 

./rploader.sh download platform

make any changes necessary and then 

backup
