### ISSUE TITLE
Failed to install DSM Failed to install the file the file is probably corrupt. VMware ESXi 7.0.2

### ISSUE THREAD

**Issue by AkideLiu** [pocopico/tinycore-redpill#45]
Try to install DSM 7.0.1 on VMware ESXi, 7.0.2, 17867351 followed this instruction: https://github.com/pocopico/tinycore-redpill

Got the error:
Failed to install DSM Failed to install the file the file is probably corrupt.

The loader could be successful boot till install in the Synology .pat system.

The log file could be found via https://github.com/RedPill-TTG/redpill-load/issues/64

**Comment by pocopico** [comment]
Its a typical no synoboot device issue. Possible reasons,

- You didnt select SATA boot at GRUB
- You need to have the loader attached to a SATA controller and not IDE 
- Connect loader to Sata 0:0 and Data Disks to 1:0, 1:1 etc
