### ISSUE TITLE
Build DS1621 Error

### ISSUE THREAD

**Issue by Striker72rus** [pocopico/tinycore-redpill#47]
tc@box:~$ sudo ./rploader.sh build v1000-7.0.1-42218
Loader source : https://github.com/jumkey/redpill-load.git Loader Branch : develop
Redpill module source : https://github.com/jumkey/redpill-lkm.git : Redpill module branch : develop
Extensions :
Extensions URL :
TOOLKIT_URL : https://sourceforge.net/projects/dsgpl/files/toolkit/DSM7.0/ds.v1000-7.0.dev.txz/download
TOOLKIT_SHA : 6108f9f7b7f0a13ee985314aef9419303375ab7ded4112be991590339b66ecd1
SYNOKERNEL_URL : https://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/25426branch/v1000-source/linux-4.4.x.txz/download
SYNOKERNEL_SHA : d3e85eb80f16a83244fcae6016ab6783cd8ac55e3af2b4240455261396e1e1be
COMPILE_METHOD : toolkit_dev
TARGET_PLATFORM       : v1000
TARGET_VERSION    : 7.0.1
TARGET_REVISION : 42218
REDPILL_LKM_MAKE_TARGET : dev-v7
KERNEL_MAJOR : 4
MODULE_ALIAS_FILE= modules.alias.4.json
Checking Internet Access -> OK
Checking if a newer version exists on the repo -> Version is current
Redpill sources already downloaded, pulling latest
Already up to date.
Loader sources already downloaded, pulling latest
Already up to date.
No extra build option specified, using default <static>
Using static compiled redpill extension
Looking for redpill for : ds1621p_42218
Getting file https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill/releases/redpill-4.4.180plus-v1000.tgz
Extracting module
Getting file https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill/src/check-redpill.sh
Got redpill-linux-v4.4.180+.ko
Testing modules.alias.4.json -> File OK
------------------------------------------------------------------------------------------------
It looks that you will need the following modules :

Found IDE Controller : pciid 8086d00007111  Required Extension :
No matching extension
Found VGA Controller : pciid 15add00000405  Required Extension : vmwgfx
Searching for matching extension for vmwgfx
Found SATA Controller : pciid 15add000007e0  Required Extension :
No matching extension
Found SATA Controller : pciid 15add000007e0  Required Extension :
No matching extension
Found SATA Controller : pciid 15add000007e0  Required Extension :
No matching extension
Found SATA Controller : pciid 15add000007e0  Required Extension :
No matching extension
[#] Checking runtime for required tools... [OK]
[#] Adding new extension from https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json...
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
######################################################################## 100.0%

[!] Extension is already added (index exists at /home/tc/redpill-load/custom/extensions/pocopico.e1000e/pocopico.e1000e.json). For more info use "ext-manager.sh info pocopico.e1000e"

*** Process will exit ***
Found Ethernet Interface : pciid 8086d0000100f Required Extension : e1000
Searching for matching extension for e1000
Found matching extension :
"https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json"
------------------------------------------------------------------------------------------------
Starting loader creation
Checking user_config.json : Done
Cache directory OK
[#] Checking runtime for required tools... [OK]
[!] There doesn't seem to be a config for DS1621+ platform running 7.0.1-42218 (checked /home/tc/redpill-load/config/DS1621+/7.0.1-42218/config.json)

*** Process will exit ***
FAILED : Loader creation failed check the output for any errors

**Comment by pocopico** [comment]
Fixed since version 7.0.0
