### ISSUE TITLE
Could not make SSH connection or start GUI

### ISSUE THREAD

**Issue by jellybean13** [pocopico/tinycore-redpill#49]
Version: 0.4.6 UEFI
Connection refused even if resetting the password of user "tc".
![image](https://user-images.githubusercontent.com/46275808/160525856-fa29f54c-adac-48a4-8063-25154681f434.png)
Also, GUI is not available.

**Comment by viktortrass** [comment]
Hello, I have the same problem, no gui and no ssh connection with VMWARE. I don't know why. any help?

**Comment by the4anoni** [comment]
I have same issue.

**Comment by viktortrass** [comment]
I used a second sata disk added to the VM and after that tinycore start correctly. and yes tinycore vmdk as SATA drive.

**Comment by jellybean13** [comment]
> I have same issue.
> 
> EDIT: Mount tinycore-redpill.v0.4.6.vmdk as SATA drive, not SCSI. Also make sure you use BIOS, not UEFI.

My board (Intel B660) is UEFI ONLY. So, legacy image is incompatible with my board.

**Comment by the4anoni** [comment]
> > I have same issue.
> > EDIT: Mount tinycore-redpill.v0.4.6.vmdk as SATA drive, not SCSI. Also make sure you use BIOS, not UEFI.
> 
> My board (Intel B660) is UEFI ONLY. So, legacy image is incompatible with my board.

This guideline is for VMware, not running tc-redpill barebone.
