### ISSUE TITLE
error update and SSL

### ISSUE THREAD

**Issue by benjamin292** [pocopico/tinycore-redpill#5]
![image](https://user-images.githubusercontent.com/97838991/149663830-fc7217ff-e293-4c6c-9d44-7d4da3e8bcac.png)

![image](https://user-images.githubusercontent.com/97838991/149663874-23d755a1-860d-48ef-97d6-b20343cfc4dd.png)

i try with HP N54L

**Comment by dertymm** [comment]
Same problem!!

**Comment by pocopico** [comment]
Try to download img again and recreate the usb disk. It looks like you are having issues with the images

**Comment by benjamin292** [comment]
Thank you for your reply.
I downloaded the 4.4 archive again and burned it to the same usb stick, I got the same error
I tried with another brand of key and it's the same...

**Comment by dertymm** [comment]
I solved it by changing to another pc

**Comment by mpuff** [comment]
i have the same problem now with v 4.5
tried different programs, win32diskimager, Rufus, than 2 different usb sticks, 2 different notebooks, but every time the same problem

**Comment by mpuff** [comment]
I did it with the similar pc, that is 1:1 the same, there it worked

**Comment by naoki66** [comment]
i have the same problem now with v tinycore-redpill.v0.4.6.vmdk

**Comment by pocopico** [comment]
You must have correct date/time for SSL to be respected
