### ISSUE TITLE
Some tools weren't available - install them first

### ISSUE THREAD

**Issue by El3ctr1cR** [pocopico/tinycore-redpill#51]
Since the rploader.sh was updated 1 hour ago I'm getting the following error when running the command: "./rploader.sh build broadwellnk-7.0.1-42218 auto":

![image](https://user-images.githubusercontent.com/36376474/160705132-9dd7d6e0-421e-459f-ac2f-ce68e8ede6f0.png)

**Comment by El3ctr1cR** [comment]
Not getting the error when im not updating the rploader (./rploader.sh update now)

**Comment by pocopico** [comment]
I think I’ve cleared this issue can you try again ?

**Comment by El3ctr1cR** [comment]
Now it's giving an syntax error:
root@box:/home/tc# ./rploader.sh serialgen DS3622xs+
./rploader.sh: line 1183: syntax error near unexpected token `}'
./rploader.sh: line 1183: `}'

**Comment by pocopico** [comment]
Fixed the typo, fixed the tools download

**Comment by xiaoyaoz1** [comment]
Some tools weren't available - install them first
怎么解决的呢？
