### ISSUE TITLE
03292022 rploader script is broken

### ISSUE THREAD

**Issue by alirz1** [pocopico/tinycore-redpill#52]
"rploader" Script is giving a syntax error after todays update

**Comment by dy0422** [comment]
The same problem.
./rploader.sh: line 1183: syntax error near unexpected token `}'
./rploader.sh: line 1183: `}'

**Comment by pocopico** [comment]
ok ! fixed typo

**Comment by pocopico** [comment]
Remove if from line 1141 

echo "Removing any old redpill.ko modules"
   **if**	[ -f /home/tc/redpill.ko ] && rm -f  /home/tc/redpill.ko 
------
echo "Removing any old redpill.ko modules"
	[ -f /home/tc/redpill.ko ] && rm -f  /home/tc/redpill.ko
