### ISSUE TITLE
dsm 7.1 42661 ds3615xs

### ISSUE THREAD

**Issue by zhonghaoyun240** [pocopico/tinycore-redpill#56]

**Comment by sarunyu** [comment]
wait too

**Comment by BlackMix** [comment]
i think this is done.

**Comment by travisghansen** [comment]
As an FYI I can't get the virtio nor e1000 drivers to work with it...only vmxnet.  virtio worked fine for me with `bromolow-7.0.1-42218`

**Comment by dipol0** [comment]
./rploader.sh build bromolow-7.0.1-42218 --->

**No space left on device**

how to fix ?

![192 168 0 216 - PuTTY_001](https://user-images.githubusercontent.com/32021806/168449295-d19e70fe-975f-4332-bd2b-f8cdea258d6d.png)

**Comment by pocopico** [comment]
Many times this has been due to low ram space. Tinycore uses 80% is RAM for the file system. The least ram you can have is 2GB

**Comment by dipol0** [comment]
> Many times this has been due to low ram space. Tinycore uses 80% is RAM for the file system. The least ram you can have is 2GB

I increase RAM upto 8Gb but have same error ((

**Comment by GuidoKuo** [comment]
build 7.0.1 same problem.how to do ?

**Comment by pocopico** [comment]
Run  ./rploader.sh clean now and try again

**Comment by dipol0** [comment]
> Run ./rploader.sh clean now and try again

I just run .**/rploader.sh build bromolow-7.1.0-42661** and OK.

PS just interetiong. I get and douload builded PAT file, run DSM on vm and then i try install it, i get Error about bat file bad/corrupded. But i get DSM7.1 PAT file from official Synology site for ds36615xs and try install it - all fine.

PPS i connect to vm with dsm 3 hdd raw images. Run it and OK, i see all 3 disks in Storage manager, But if i try connect 4 image DSM not see it. ??? Need every time rebuild loader with **./rploader.sh satamap now** if new disk connected? Or i can once modify user_config.json as example like?:

    "SataPortMap": "9",
    "DiskIdxMap": "00"

![Выделение_200](https://user-images.githubusercontent.com/32021806/168470492-a85d53e0-5f0e-4b74-b12b-77ac176f31b3.png)
