### ISSUE TITLE
sataProtMap has  a  value bigger than  9

### ISSUE THREAD

**Issue by entroxu** [pocopico/tinycore-redpill#60]
use this scrip "./rploader.sh statamap now"

the shell show message like this :
HBA: 00:12.0 Disks : 2
HBA: 00:13.0 Disks : 12
HBA: 00:13.2 Disks : 12
SataPortMap=21212
DiskIdxMap=000C18

I guess there are three controllers but as other article says SataPortMap means one digit has one controller  which means there are five controllers?

but if there are three controllers ,12 is bigger than 9.

is this  a problem of this  script ,or script is correct?

**Comment by pocopico** [comment]
Yes, the script is not correct. It fails to identify correctly this setting most of the times. SataPortMap is a single digit decimal per controller variable

**Comment by entroxu** [comment]
OK，than you .
can I ask one more question ，what does "HBA: 00:13.0 Disks : 12" means ?
