### ISSUE TITLE
Setting default boot entry

### ISSUE THREAD

**Issue by ibaklykov** [pocopico/tinycore-redpill#63]
When script finishes I get the following message:
```
menuentry 'RedPill DS3615xs v7.0.1-42218 (USB, Verbose)' {
menuentry 'RedPill DS3615xs v7.0.1-42218 (SATA, Verbose)' {
menuentry 'Tiny Core Image Build' {
Machine is VIRTUAL Hypervisor=KVM
Setting default boot entry to SATA
```
Is it possible to change default boot entry to USB ?
I have to select it manually each time the VM is starting.

**Comment by pocopico** [comment]
I can change the default for KVM to USB if you thi j

**Comment by ibaklykov** [comment]
> It’s only for the first time, after that the default is re-saved to grub env

You're right! After installing DSM the default boot entry has changed to USB itself. It was a false alarm... sorry.
Thank you!
