### ISSUE TITLE
any body install 918+ 7.1 success in unraid 6.9.0?

### ISSUE THREAD

**Issue by zhudan** [pocopico/tinycore-redpill#67]
any body install 918+ 7.1 success in unraid 6.9.0?

I tried it, and it prompted a hard disk format error during installation

**Comment by goldenbilla** [comment]
i install 7.0 and it is working fine. but having issue satamapping when passthrough sata controller.

**Comment by zhudan** [comment]
has been resolved. The vdisk space given is too small, and it is solved by 25G. The specific size has not been tested.
