### ISSUE TITLE
About 920+ dts in PVE，VMware，Esxi

### ISSUE THREAD

**Issue by wjz304** [pocopico/tinycore-redpill#68]
由于设备的环境不同，执行以下命令后的结果 可能显示不同的的层级，
udevadm info --query path --name $(lsblk | grep -i disk | grep -i sd | awk '{print $1}' | grep -v $(mount | grep -i optional | grep cde | awk -F / '{print $3}' | uniq | cut -c 1-3))

比如:
/devices/pci0000:00/0000:00:05.0/ata2/host1/target1:0:0/1:0:0:0/block/sdb
/devices/pci0000:00/0000:00:11.0/0000:02:04.0/ata2/host1/target1:0:0/1:0:0:0/block/sdb
/devices/pci0000:00/0000:00:1e.0/0000:05:01.0/0000:06:07.0/ata7/host6/target6:0:0/6:0:0:0/block/sdb

因此我在 function patchdtc() 中做了一个判断，

diskdepth=$(udevadm info --query path --name $disk | awk -F"/" '{print NF-1}')
if [[ $diskdepth = 9 ]]; then
    diskpath=$(udevadm info --query path --name $disk | awk -F "\/" '{print $4 ":" $5 }' | awk -F ":" '{print $2 ":" $3 }')
elif  [[ $diskdepth = 11 ]]; then
    diskpath=$(udevadm info --query path --name $disk | awk -F "\/" '{print $4 ":" $5 ":" $6 }' | awk -F ":" '{print $2 ":" $3 "," $6 "," $9 }')
else
    diskpath=$(udevadm info --query path --name $disk | awk -F "\/" '{print $4 ":" $5 }' | awk -F ":" '{print $2 ":" $3 "," $6}')
fi

**Comment by wjz304** [comment]
能力有限 我shell并不是很精通，所以上述代码没有验证，也没有更好的判断方法，希望大神能参考一下

**Comment by pocopico** [comment]
I like it but its very complicated to match all different case.
