### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by Honanhui** [pocopico/tinycore-redpill#69]
tc@box:~$ sudo ./rploader.sh build broadwellnk-7.1.0-42661
ln: failed to create symbolic link '/home/tc/custom-module/auxfiles': Operation not permitted
Rploader Version : 0.7.0.5
Loader source : https://github.com/pocopico/redpill-load.git Loader Branch : develop 
Redpill module source : https://github.com/dogodefi/redpill-lkm.git : Redpill module branch : develop 
Extensions :   redpill-misc 
Extensions URL : "https://github.com/pocopico/redpill-load/raw/master/redpill-misc/rpext-index.json"
TOOLKIT_URL : https://sourceforge.net/projects/dsgpl/files/toolkit/DSM7.0/ds.broadwellnk-7.0.dev.txz/download
TOOLKIT_SHA : 0d9edca67d9e7e14c2529bbb58341b623936124d5264f71f1e4acbacf3ea202d
SYNOKERNEL_URL : https://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/25426branch/broadwellnk-source/linux-4.4.x.txz/download
SYNOKERNEL_SHA : d3e85eb80f16a83244fcae6016ab6783cd8ac55e3af2b4240455261396e1e1be
COMPILE_METHOD : toolkit_dev
TARGET_PLATFORM       : broadwellnk
TARGET_VERSION    : 7.1.0
TARGET_REVISION : 42661
REDPILL_LKM_MAKE_TARGET : dev-v7
KERNEL_MAJOR : 4
MODULE_ALIAS_FILE :  modules.alias.4.json
SYNOMODEL : ds3622xsp_42661 
MODEL : DS3622xs+ 
Local Cache Folder : /mnt/sda3/auxfiles
Checking Internet Access -> OK
Checking if a newer version exists on the repo -> Version is current
Redpill sources already downloaded, pulling latest
Already up to date.
Loader sources already downloaded, pulling latest
fatal: not a git repository (or any of the parent directories): .git
No extra build option specified, using default <static> 
Using static compiled redpill extension
Removing any old redpill.ko modules
Looking for redpill for : ds3622xsp_42661 
Getting file https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill/releases/redpill-4.4.180plus-broadwellnk.tgz
Extracting module
Getting file https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill/src/check-redpill.sh
Got redpill-linux-v4.4.180+.ko 
Testing modules.alias.4.json -> File OK
------------------------------------------------------------------------------------------------
It looks that you will need the following modules : 

Found IDE Controller : pciid 8086d00007111  Required Extension : 
No matching extension
parse error: Expected another key-value pair at line 1209, column 3
Found VGA Controller : pciid 15add00000405  Required Extension : vmwgfx
Searching for matching extension for vmwgfx
parse error: Expected another key-value pair at line 1209, column 3
Found SCSI Controller : pciid 1000d00000030  Required Extension : mptspi
Searching for matching extension for mptspi
parse error: Expected another key-value pair at line 1209, column 3
[#] Checking runtime for required tools... [OK]
[#] Adding new extension from https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json... 
[#] Downloading remote file https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json to /home/tc/redpill-load/custom/extensions/_new_ext_index.tmp_json
[-] https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json
[-] rpext-index.json
[-] json
[-] https://ghproxy.llm-y2k.workers.dev/https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json
-=O=-      #   #     #    #                                                   

[!] Extension is already added (index exists at /home/tc/redpill-load/custom/extensions/pocopico.e1000e/pocopico.e1000e.json). For more info use "ext-manager.sh info pocopico.e1000e"

*** Process will exit ***
Found Ethernet Interface : pciid 8086d0000100f Required Extension : e1000
Searching for matching extension for e1000
Found matching extension : 
"https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json"
Found SATA Controller : pciid 15add000007e0  Required Extension : 
No matching extension
------------------------------------------------------------------------------------------------
Starting loader creation 
Found tinycore cache folder, linking to home/tc/custom-module
Checking user_config.json : Done
Entering redpill-load directory
Removing bundled exts directories
Found build request for revision greater than 42218
Found extractor locally cached
Copying required libraries to local lib directory
Linking lib to lib64
Copying executable
Removing temp folder /tmp/synoesp
Checking if tool is accessible
/bin/syno_extract_system_patch: /usr/local/lib/libcurl.so.4: no version information available (required by /bin/syno_extract_system_patch)
Executed succesfully
Creating temp folder /tmp/pat 
Checking for cached pat file
Found tinycore cache folder, linking to home/tc/custom-module
Found locally cached pat file /home/tc/custom-module/ds3622xsp_42661.pat
File /home/tc/custom-module/ds3622xsp_42661.pat, is  encrypted
Extracting encrypted pat file : /home/tc/custom-module/ds3622xsp_42661.pat to /tmp/pat
/bin/syno_extract_system_patch: /usr/local/lib/libcurl.so.4: no version information available (required by /bin/syno_extract_system_patch)
Creating unecrypted pat file ds3622xsp_42661.pat to /home/tc/redpill-load/cache folder 
./VERSION
Pat file  sha256sum is : a8cd788e901de75f6113c1f6177a25b1b6517c4199f988e1066076cb9747fb69
Checking config file existence -> No config file found, please use the proper repo, clean and download again

What's going on?

**Comment by pocopico** [comment]
do a clean and start over
