### ISSUE TITLE
TS453Dmini install DS920+ DSM7.1 Problem Fix

### ISSUE THREAD

**Issue by huangfengye** [pocopico/tinycore-redpill#72]
run
```
./rploader.sh update now
./rploader.sh fullupgrade now
./rploader.sh serialgen DS920+
./rploader.sh identifyusb now
./rploader.sh satamap now 
```
result
```
HBA: 00:12.0 Disks : 2
HBA: 00:13.0 Disks : 12
SataPortMap=212
DiskIdxMap=000C
```
this is wrong // or SataPortMap and DiskIdxMap not work on ds920p model?
fix in user_config.json
```
SataPortMap=22
DiskIdxMap=0002
```
run  // add r8125 driver here 
```
./rploader.sh ext geminilake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/main/r8125/rpext-index.json
./rploader.sh build geminilake-7.0.1-42218
./rploader.sh clean now
./rploader.sh ext geminilake-7.1.0-42661 add https://raw.githubusercontent.com/pocopico/rp-ext/main/r8125/rpext-index.json
```
I have to edit the ds920p.dts file in  .tc\  
and upload it to .tc\redpill-load\,  
/rploader.sh alway generate a wrong dts file,  this is the right one

![image](https://user-images.githubusercontent.com/26798988/166176017-cb275384-5bb5-4c88-ad03-72e65966c0b8.png)

also the rploader.sh keep make a  new dts ....
so i have to edit it ,delete some code from function patchdtc() in rploader.sh
![image](https://user-images.githubusercontent.com/26798988/166176200-e442f416-5e50-4702-a89e-661ba6b7edbe.png)

run
```
./rploader.sh build geminilake-7.1.0-42661
```
if the shell tell you have new repo update, just choose no  'n'
```
sudo filetool.sh -b
sudo reboot
```
result, all disk show with right position, perfact 
![image](https://user-images.githubusercontent.com/26798988/166178859-bad8e94a-9274-43a6-a374-29b3543055d1.png)
![image](https://user-images.githubusercontent.com/26798988/166178875-b1f6980c-de21-4105-a958-abdd52c48525.png)

**Comment by pocopico** [comment]
Hi,

you can use 

./rploader.sh build geminilake-7.1.0-42661 manual
