### ISSUE TITLE
ESXi 7.0 "gzip: stdout: No space left on device"

### ISSUE THREAD

**Issue by bzfzis** [pocopico/tinycore-redpill#74]
Checking for cached pat file
Found tinycore cache folder, linking to home/tc/custom-module
Found locally cached pat file /home/tc/custom-module/ds3622xsp_42661.pat
File /home/tc/custom-module/ds3622xsp_42661.pat, is  encrypted
Extracting encrypted pat file : /home/tc/custom-module/ds3622xsp_42661.pat to /tmp/pat
/bin/syno_extract_system_patch: /usr/local/lib/libcurl.so.4: no version information available (required by /bin/syno_extract_system_patch)
Creating unecrypted pat file ds3622xsp_42661.pat to /home/tc/redpill-load/cache folder 

gzip: stdout: No space left on device
tar: /home/tc/redpill-load/cache/ds3622xsp_42661.pat: Wrote only 2048 of 10240 bytes
tar: Child returned status 1
tar: Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Pat file  sha256sum is : a14d84a552c21427cb03373f1f2f79be059af7ea1ac4ae7d77adcbb982ee5a2f
Checking config file existence -> No config file found, please use the proper repo, clean and download again

**Comment by pocopico** [comment]
Increase the system RAM or change the extract location

**Comment by bzfzis** [comment]
Thanks😉
