### ISSUE TITLE
Error Booting with USb hard disk attached on UEFI BIOS

### ISSUE THREAD

**Issue by sdhawade** [pocopico/tinycore-redpill#77]
If there is a USB HDD the boot fails with error : disk 'hd0,msdos3' not found. Refer attached image
![2](https://user-images.githubusercontent.com/8513435/168539521-8a16b066-d899-447c-a20d-4e1506ae9ce7.jpeg)
![1](https://user-images.githubusercontent.com/8513435/168539528-26c8ddbf-50bd-4715-82cc-2c0265230baa.jpeg)
s

**Comment by mattfrias** [comment]
currently having the same issue, did you find a fix?

**Comment by simkoG** [comment]
@sdhawade, did you find a solution to this problem?

**Comment by sdhawade** [comment]
Yes I did, Got this working after a few trials. It seems the USB disk to boot from is hard coded in GRUB as hd0, msdosx where x is the Tinycore or the Synology boot partition built by redpill-load. Depending on your motherboard and other USB disks attached you may get lucky and your USB stick will show up as hd0. If it doesnt you have 2 options 

1. Keep changing the order of where you plug in your devices into USB so that the USB stick is identified as hd0.

2. edit grub.cfg to match the hd number you have. This is easy to find out by jumping into the grub shell at the boot menu by hitting 'c' and type ls at the prompt. This should show you all the disks and the partition idetifiers as per grub.

**Comment by WMP** [comment]
I need to change hd0/msdos3 to hd0,msdos1. Grub dont know filesystem on msdos3.

**Comment by joonheeu** [comment]
I resolved it using the command 'set root=(hd1,msdos3)'

**Comment by WMP** [comment]
I found the reason why grub looks for partitions on msdos3 and not on msdos1.  In some files ex: https://github.com/pocopico/tinycore-redpill/blob/c4154d5fd2490fcc2e0b8be22619cc04b744846b/config/RS3413xs%2B/7.1.0-42661/config.json https://github.com/pocopico/tinycore-redpill/blob/c4154d5fd2490fcc2e0b8be22619cc04b744846b/config/FS2500/7.1.0-42661/config.json https://github.com/pocopico/tinycore-redpill/blob/c4154d5fd2490fcc2e0b8be22619cc04b744846b/config/RS3618xs/7.1.0-42661/config.json is writed msdos3. 

There are differences between versions, e.g. for DVA3221 version 7.1.0-42661 https://github.com/pocopico/tinycore-redpill/blob/c4154d5fd2490fcc2e0b8be22619cc04b744846b/config/DVA3221/7.1.0-42661/config.json msdos3 is defined and for DVA3221 version https://github.com/pocopico/tinycore-redpill/blob/c4154d5fd2490fcc2e0b8be22619cc04b744846b/config/DVA3221/7.1.1-42962/config.json msdos1 is defined.

When I changed the version from DVA3221 version 7.1.0-42661 (config.jcon has msdos3) to DVA3221 7.1.1-42962 (config json has msdos1) the problem resolved.

**Comment by joonheeu** [comment]
> I found the reason why grub looks for partitions on msdos3 and not on msdos1. In some files ex: https://github.com/pocopico/tinycore-redpill/blob/c4154d5fd2490fcc2e0b8be22619cc04b744846b/config/RS3413xs%2B/7.1.0-42661/config.json https://github.com/pocopico/tinycore-redpill/blob/c4154d5fd2490fcc2e0b8be22619cc04b744846b/config/FS2500/7.1.0-42661/config.json https://github.com/pocopico/tinycore-redpill/blob/c4154d5fd2490fcc2e0b8be22619cc04b744846b/config/RS3618xs/7.1.0-42661/config.json is writed msdos3.
> 
> There are differences between versions, e.g. for DVA3221 version 7.1.0-42661 https://github.com/pocopico/tinycore-redpill/blob/c4154d5fd2490fcc2e0b8be22619cc04b744846b/config/DVA3221/7.1.0-42661/config.json msdos3 is defined and for DVA3221 version https://github.com/pocopico/tinycore-redpill/blob/c4154d5fd2490fcc2e0b8be22619cc04b744846b/config/DVA3221/7.1.1-42962/config.json msdos1 is defined.
> 
> When I changed the version from DVA3221 version 7.1.0-42661 (config.jcon has msdos3) to DVA3221 7.1.1-42962 (config json has msdos1) the problem resolved.

After resolving the issue and entering the terminal, can you guide me on which guide to follow next?
