### ISSUE TITLE
UEFI Boot Support?

### ISSUE THREAD

**Issue by chchia** [pocopico/tinycore-redpill#8]
Hi Thank you, i tried to boot in UEFI but failed, both tinycore and the loader.img.

i can boot it with MBR.

any planning to add UEFI boot support?

**Comment by miholeus** [comment]
+1, @pocopico do you plan to add uefi? Unfortunately, I can't use csm mode((

**Comment by kills** [comment]
+1 I would also appreciate UEFI Support

**Comment by Plarkass** [comment]
+1 Can be nice to have it

**Comment by kills** [comment]
Following along with this guide, I was able to modify the USB stick:
https://github.com/ndeineko/grub2-bios-uefi-usb

**Comment by Plarkass** [comment]
> Following along with this guide, I was able to modify the USB stick: https://github.com/ndeineko/grub2-bios-uefi-usb

How do you achive it ?
You full format then create the UEFI boot and then copy grub to partition 1 ?
 Could you please provide us by a commit or branch img file or give us the proper way to do it please ?

**Comment by kills** [comment]
That's it :) Glad you got it!

**Comment by dreamtekcat** [comment]
Still cant boot tinycore.img in ovmf(uefi) proxmox 7 vm, any solution?

**Comment by ac-xa** [comment]
> Still cant boot tinycore.img in ovmf(uefi) proxmox 7 vm, any solution?

I'm not using proxmox but I tried to see if I can make it work. Here is what worked for me.
1. Upload tinycore-redpill-uefi.v0.4.5.img.gz to proxmox in folder /var/lib/vz/images/
2. unpack tinycore-redpill-uefi.v0.4.5.img.gz to tinycore-redpill-uefi.v0.4.5.img
3. rename tinycore-redpill-uefi.v0.4.5.img to tinycore.img
4. Set your VM bios to OVMF (UEFI)
5. Add following to vm config (ie  /etc/pve/qemu-server/100.conf)
`args: -device 'qemu-xhci,addr=0x18' -drive 'id=my_usb_disk,file=/var/lib/vz/images/tinycore.img,if=none,format=raw' -device 'usb-storage,id=my_usb_disk,drive=my_usb_disk,bootindex=5'`

For reference my config looks like this:
```
args: -device 'qemu-xhci,addr=0x18' -drive 'id=my_usb_disk,file=/var/lib/vz/images/tinycore.img,if=none,format=raw' -device 'usb-storage,id=my_usb_disk,drive=my_usb_disk,bootindex=5'
bios: ovmf
boot: order=sata0;net0
cores: 2
memory: 2048
name: test
net0: e1000=FA:A7:1A:9D:A2:40,bridge=vmbr0,firewall=1
numa: 0
ostype: l26
sata0: local-lvm:vm-100-disk-0,size=8G
scsihw: virtio-scsi-pci
smbios1: uuid=c17d8446-9f13-4af4-96ea-6bcaed77e5ea
sockets: 1
vmgenid: d89fa586-cb9b-475e-87ac-873d2babb8ba

```
