### ISSUE TITLE
1231

### ISSUE THREAD

**Issue by wincol1151** [pocopico/tinycore-redpill#83]

**Comment by wincol1151** [comment]
我发现我提出了一个莫名其妙的问题 被关闭了  这个怪我 我一个小白 不太会用GitHub  当初我以为这个是给项目取名字呢 所以就随手填了1231  看来 要学的还挺多的

**Comment by pocopico** [comment]
No problem 😉

**Comment by pocopico** [comment]
What platform are you using ?

**Comment by wincol1151** [comment]
我用的也是 https://github.com/tossp/redpill-tool-chain 这个

**Comment by wincol1151** [comment]
还有一个现实问题 我的主板h61  网卡RTL8111e  这个添加哪个驱动呢 我试了几个 都找不到IP

**Comment by wincol1151** [comment]
这个问题解决了 最总 添加了 RTL8169 就可以了
