### ISSUE TITLE
multiple errors in file lines on jq command not found

### ISSUE THREAD

**Issue by sojab0on** [pocopico/tinycore-redpill#9]
i have booted your VMDK file in a clean VM 
It boot st TinyCore and i could change the tc user password 

Afterwards i used scp to push over the files from the zip file 

but now when i try to run the interactive or rploader.sh files it constantly states 
bin/sh command not found 

Why is this

**Comment by sojab0on** [comment]
Have them running now but the interactive menus dont do anyting
als the update command goes to say new script version found but when i say yes it states it cannot find latestrploader.sh 
the serial gen command fails also 
on invallid option -- 's'
it doesnt matter witch system i give in DS3615xs 3617xs or 918+

**Comment by sojab0on** [comment]
I did this all with the vmdk tc boot drive file and it doesnt matter what commands i use constant errors with jq on lines and it cant even write the serialgen info to the files

**Comment by sojab0on** [comment]
I fixed it by using workstation pro to setup a vm and convert it to ESXI 7.0 hardware specs with right linux 3.0 kernel x64 mode 
It booted to gui and i could run the rpload now but i can seen to get the boot loader to boot i changed the user cofig file to reflect the correct mac address and tried satamap 1 and the other 00 as the script states to fix it but it wont boot to be findable

**Comment by pocopico** [comment]
Fixed
