### ISSUE TITLE
Couldn't find bspatch in your $PATH

### ISSUE THREAD

**Issue by dookei** [pocopico/tinycore-redpill#91]
Hi there,
I am facing an issue when loading the **./rploader.sh bromolow-7.0.1-42218** 
I get always an error saying "**Couldn't find bspatch in your $PATH**"
Any thoughts on what might be wrong?

**Comment by dookei** [comment]
https://github.com/pocopico/tinycore-redpill/issues/26

**Comment by pocopico** [comment]
Fixed on latest version
