### ISSUE TITLE
Please add support for DVA1622

### ISSUE THREAD

**Issue by dimadusk** [pocopico/tinycore-redpill#99]
Great job, many thanks, successfully ran DVA3221 baremetal on Gigabyte Brix N2807 (Celeron N2807), also tried on big pc with Nvidia GTX 1660, AI features work perfect. But DVA1622 model is more interesting since it doesnt require Nvidia GPU, this model is based on Intel Celeron J4105 and all face recognition and license plate recognition features work just as on Nvidia gpu but on built-in gpu from Intel. Its "openvino" arch. SurveillanceStation-x86_64-9.0.0-7660_openvino.spk

**Comment by pocopico** [comment]
Interesting. Surely we might try

**Comment by pocopico** [comment]
Its been added
